### ISSUE TITLE
Brokered: java.lang.NullPointerException when artemis is under load of connections

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1169]
Artemis in brokered address space throws java.lang.NullPointerException when rhea client tries to create lot of connections (>200). 
 - With standalone broker with tls client is able to create more than 1K of connections without problem.
 - Brokered address space with **NONE** auth service has same behavior as standalone broker (can handle more than 1000 connection)

I use connections.js reproducer for this.
[connections.js.txt](https://github.com/EnMasseProject/enmasse/files/1946086/connections.js.txt)

reproducer:
1. create brokered address space with standard auth service
2. create queue address
3. run 
```sh
node connections.js --host [messaging-route] -p 443 -a [address-name] --timeout 5000 -c 500 --username test --password test -f true
```

client errors
```
...
[connection-289] error: {"message":"socket hang up"}
[connection-289] error: {"message":"101057795:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:openssl\\ssl\\s3_pkt.c:1217:\n"}
...
```

artemis log
```
...
2018-04-25 07:58:55,627 WARN  [io.netty.handler.ssl.SslHandler] [id: 0x41c80bd1, L:/172.17.0.10:5671 ! R:/172.17.0.1:51302] flush() raised a masked exception.: java.lang.NullPointerException
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:742) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:734) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1595) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:165) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler$1.run(SslHandler.java:631) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [artemis-commons-2.5.0.jar:2.5.0]
2018-04-25 08:07:03,641 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2018-04-25 08:07:03,642 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2018-04-25 08:07:15,381 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2018-04-25 08:07:22,651 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2018-04-25 08:07:22,652 ERROR [org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred.
2018-04-25 08:07:24,509 WARN  [io.netty.handler.ssl.SslHandler] [id: 0xbc300c09, L:/172.17.0.10:5671 ! R:/172.17.0.1:39970] flush() raised a masked exception.: java.lang.NullPointerException
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:742) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:734) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:1595) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler.access$600(SslHandler.java:165) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.ssl.SslHandler$1.run(SslHandler.java:631) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [artemis-commons-2.5.0.jar:2.5.0]
...
```

**Comment by kornys** [comment]
@rgodfrey I think that this issue should be fixed in next sprint as well.

**Comment by k-wall** [comment]
@kornys is this still reproducible against the latest Enmasse build (that uses Artemis 2.6.2)? Is there a known upstream Artemis issue logged?

**Comment by kornys** [comment]
@k-wall I have to re-test with latest enmasse, anyway no upstream/downstream artemis issue was raised. I don't think so it is a artemis issue, because with standalone broker reproducer worked fine

**Comment by k-wall** [comment]
@kornys Thanks.  I suppose it is possible the Enmasse SASL plugins might be having bearing and somehow provoking Artemis to fail, but the appearance of the NPE from the Artemis code says to me that the error handling needs some work.  Even if the error is harmless it still makes the system as a whole more difficult to support as folks need to continually reason about the error.

It would be good to get a simple reproduction over to the Broker team, so it can get fixed.  If you can confirm that you still see the problem against the test case, I can take a look and see if I can make a stand alone reproducer and get the details over to them.

**Comment by kornys** [comment]
@k-wall I have tested it again with same reproducer and this null pointer issues was not appear, but there are still a lot of "[org.apache.activemq.artemis.core.server] AMQ224088: Timeout (10 seconds) while handshaking has occurred." errors when I raise number of connection to 500 for example. And client still contains [connection-289] error: {"message":"socket hang up"}. Anyway SSl handler exception is fixed I guess.

**Comment by k-wall** [comment]
Closing as the original reported NPE is gone.  @kornys it would be good to raise a separate issue about your follow on observation.
