### ISSUE TITLE
Fix unstable test enmasse.queue.scheduler.ArtemisTest.testManagement

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#123]
See https://travis-ci.org/EnMasseProject/enmasse/builds/263442523#L3647

    java.lang.AssertionError: 
    Expected: is <2L>
         but: was <0L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at enmasse.queue.scheduler.ArtemisTest.testManagement(ArtemisTest.java:68)

**Comment by lulf** [comment]
Not used anymore
