### ISSUE TITLE
Provision via Service catalog doesn't work due to missing "namespace"

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#1233]
Looks like we(@kornys) found critical issue with service catalog (OSB)

**Description:** Creating address space "addressspace1" via service catalog doesn't work. 
1. Project "addressspace1" with provisioned service was created, but it'll be never ready (with message: "The service is not yet ready. The instance is being provisioned asynchronously")
2. Log of service-broker pod in MyProject contains: 
```
2018-05-18 08:48:39 INFO  OSBProvisioningService:53 - identity: {"groups":["system:authenticated:oauth","system:authenticated"],"scopes.authorization.openshift.io":["user:full"],"uid":"","username":"developer"}
2018-05-18 08:48:40 INFO  OSBProvisioningService:83 - Created MaaS addressspace addressspace1
2018-05-18 08:48:40 INFO  OSBProvisioningService:99 - Returning ProvisionResponse with dashboardUrl https://172.30.106.155:8443/console/addressspace1 
2018-05-18 08:48:40 INFO  OSBProvisioningService:53 - identity: {"groups":["system:authenticated:oauth","system:authenticated"],"scopes.authorization.openshift.io":["user:full"],"uid":"","username":"developer"}
2018-05-18 08:48:40 ERROR ConfigMapAddressSpaceApi:59 - Error creating addressspace1
2018-05-18 08:48:40 INFO  DefaultExceptionMapper:51 - Returning client error HTTP status 409: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/myproject/configmaps . Message: configmaps "nulladdressspace1" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=nulladdressspace1, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=configmaps "nulladdressspace1" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
2018-05-18 08:48:40 INFO  OSBLastOperationService:37 - Received last_operation request for instance 68763dcf-f39a-48cb-9969-208e5f0fd483, operation provision, service id 1e1b59e2-75bc-3e20-bf7b-ae9e07ecdff3, plan id 1f3ae309-e188-3c2f-b8cd-5ffe8e3cf5ea
2018-05-18 08:48:40 INFO  OSBLastOperationService:45 - No such address space found
2018-05-18 08:48:41 INFO  OSBLastOperationService:37 - Received last_operation request for instance 68763dcf-f39a-48cb-9969-208e5f0fd483, operation provision, service id 1e1b59e2-75bc-3e20-bf7b-ae9e07ecdff3, plan id 1f3ae309-e188-3c2f-b8cd-5ffe8e3cf5ea
2018-05-18 08:48:41 INFO  OSBLastOperationService:45 - No such address space found
2018-05-18 08:48:45 INFO  OSBLastOperationService:37 - Received last_operation request for instance 68763dcf-f39a-48cb-9969-208e5f0fd483, operation provision, service id 1e1b59e2-75bc-3e20-bf7b-ae9e07ecdff3, plan id 1f3ae309-e188-3c2f-b8cd-5ffe8e3cf5ea
2018-05-18 08:48:45 INFO  OSBLastOperationService:45 - No such address space found
2018-05-18 08:48:53 INFO OSBLastOperationService:37 - Received last_operation request for instance 68763dcf-f39a-48cb-9969-208e5f0fd483, operation provision, service id 1e1b59e2-75bc-3e20-bf7b-ae9e07ecdff3, plan id 1f3ae309-e188-3c2f-b8cd-5ffe8e3cf5ea
```
3. log of address-space-controller contains:
```
2018-05-18 08:47:24 INFO  ControllerChain:109 - Check standard address spaces: []
2018-05-18 08:47:54 INFO  ControllerChain:109 - Check standard address spaces: []
2018-05-18 08:48:24 INFO  ControllerChain:109 - Check standard address spaces: []
2018-05-18 08:48:40 INFO  FifoQueue:80 - Processing event Added with key nulladdressspace1
2018-05-18 08:48:40 INFO  Reflector:55 - Waiting on event queue for 42901 ms unless notified
2018-05-18 08:48:40 INFO  ControllerChain:109 - Check standard address spaces: [addressspace1]
2018-05-18 08:48:40 WARN  ControllerChain:124 - Error syncing address space addressspace1
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/apis/project.openshift.io/v1/projectrequests . Message: ProjectRequest "" is invalid: metadata.name: Required value: name or generateName is required. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Required value: name or generateName is required, reason=FieldValueRequired, additionalProperties={})], group=null, kind=ProjectRequest, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ProjectRequest "" is invalid: metadata.name: Required value: name or generateName is required, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.openshift.client.dsl.internal.ProjectRequestsOperationImpl.create(ProjectRequestsOperationImpl.java:74)
	at io.fabric8.openshift.client.dsl.internal.ProjectRequestsOperationImpl$1.apply(ProjectRequestsOperationImpl.java:91)
	at io.fabric8.openshift.client.dsl.internal.ProjectRequestsOperationImpl$1.apply(ProjectRequestsOperationImpl.java:87)
	at io.fabric8.openshift.api.model.DoneableProjectRequest.done(DoneableProjectRequest.java:27)
	at io.enmasse.controller.common.KubernetesHelper.createNamespace(KubernetesHelper.java:85)
	at io.enmasse.controller.CreateController.handle(CreateController.java:57)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:119)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
2018-05-18 08:48:40 WARN  LogEventLogger:22 - AddressSpaceSyncFailed (kind=AddressSpace name=addressspace1): Error syncing address space: Failure executing: POST at: https://172.30.0.1/apis/project.openshift.io/v1/projectrequests . Message: ProjectRequest "" is invalid: metadata.name: Required value: name or generateName is required. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Required value: name or generateName is required, reason=FieldValueRequired, additionalProperties={})], group=null, kind=ProjectRequest, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ProjectRequest "" is invalid: metadata.name: Required value: name or generateName is required, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
2018-05-18 08:48:40 WARN  ResourceChecker:53 - Exception in checker task
java.lang.NullPointerException
	at io.enmasse.controller.ControllerChain.retainAddressSpaces(ControllerChain.java:132)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:128)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
2018-05-18 08:49:10 INFO ControllerChain:109 - Check standard address spaces: [addressspace1]
```
4. MyProject's ConfigMaps contains: " nulladdressspace1" with **namespace: null**
```
{"apiVersion":"enmasse.io/v1","kind":"AddressSpace","metadata":{"name":"addressspace1","namespace":null,"labels":{"serviceInstanceId":"68763dcf-f39a-48cb-9969-208e5f0fd483"},"annotations":{"enmasse.io/created-by":"developer","enmasse.io/created-by-uid":"6bcdb98c-5a77-11e8-ace5-525400e26b8e"}},"spec":{"type":"brokered","plan":"unlimited-brokered","authenticationService":{"type":"standard","details":{}}},"status":{"isReady":false}}
```
**Reproducer:**
Reproducible via "ServiceCatalogWebTest" automated tests from following branch: https://github.com/EnMasseProject/enmasse/tree/service-catalog-web
```
Xvfb :10 -ac &
DISPLAY=:10 make SKIP_CLEANUP=false MULTITENANT=true OPENSHIFT_PROJECT="myproject" SYSTEMTEST_ARGS='ServiceCatalogWebTest' systemtests
```

**Comment by lulf** [comment]
@tkratky Awesome to have some tests for the service broker now :) This is a bug introduced by me when I merged the api changes. I will fix the OSB provisioning service to set the new parameters required when creating the configmap

**Comment by kornys** [comment]
@lulf that is why we with @tkatky try to make tests as soon as new features are implemented :)
