### ISSUE TITLE
Using empty addressSpace endpoint list along with services doesn't work anymore

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1398]
As a way of configuring external loadbalancer annotations and properties in endpoints (see #661), we create an addressSpace with an empty endpoint list (`"endpoints": [],`)  and deploy our own endpoint services (with `type: LoadBalancer` label), so that these are adopted as endpoints via `EndpointController.updateEndpoints()`.

With EnMasse 0.21.0 however, this doesn't work anymore. There is this exception, occuring repeatedly:
````
2018-06-21 13:32:13.335 [Thread-4] INFO  ControllerChain:109 - Check address spaces: [hono:default]
2018-06-21 13:32:13.354 [Thread-4] INFO  CreateController:72 - Creating address space {name=default,namespace=hono,type=standard,plan=unlimited-standard-without-mqtt,endpoints=[],status={isReady=false,endpointStatuses=[],messages=[]}}
2018-06-21 13:32:14.088 [Thread-4] WARN  ResourceChecker:53 - Exception in checker task
java.lang.IllegalArgumentException: No value available for parameter name: CONSOLE_SECRET
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:203)
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:157)
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
  at io.enmasse.controller.common.KubernetesHelper.processTemplate(KubernetesHelper.java:123)
  at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:85)
  at io.enmasse.controller.CreateController.handle(CreateController.java:104)
  at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:120)
  at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
  at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
  at java.lang.Thread.run(Thread.java:748)
````

Related commit:
https://github.com/EnMasseProject/enmasse/commit/12d3ebbf07d0d83541136d99d8b5db08dc8631ea#diff-c1906ad2f12f179d2ea72800cf87281cL85

(The `Step 3: Create missing secrets if not specified` in `TemplateInfraResourceFactory.createResourceList` has been removed, so template params aren't set anymore.)

**Comment by lulf** [comment]
This is clearly something we’re missing a test for, thanks for reporting. This got introduced in the endpoint spec /status split, we should fix it

FWIW a workaround could be to let them be created, and then subsequently remove them (as you’ve done earlier i suppose)

**Comment by calohmn** [comment]
Thanks!
