### ISSUE TITLE
Performance impact of having only single qpid-to-broker connection

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1431]
We've done some load tests using a standard address space, sending 500 byte messages from 300 clients, each creating an AMQP connection.

Looking at the CPU usage in the broker, the java process takes up 180-200% throughout the test.
When switching to the threads-based view, there is always the same **one thread** that is taking up 93-99% CPU.
That thread is one of the "ActiveMQ-client-netty-threads" threads. There only being _one_ such thread involved here corresponds to the _one_ AMQP connection between Qpid and broker. This looks like a bottleneck.

(EnMasse 0.20.0 with Artemis 2.6.1 image using OpenSSL as sslProvider.)

**Comment by calohmn** [comment]
Screenshot of a JVisualVM CPU sampling result concerning the above mentioned thread:
![artemis_thread0_protonhandler_inputbuffer](https://user-images.githubusercontent.com/891931/42511438-2eaf52e6-8452-11e8-8e0f-041374b64d8c.png)

Note the times for `lock()` and `unlock()`.

A thread dump shows how this thread is WAITING (parked) at times:
The 99% CPU thread:
````
"Thread-0 (ActiveMQ-client-netty-threads)" - Thread t@29
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- waiting to lock <6d7b6705> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "Thread-26 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@609db43b)" t@74
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.inputBuffer(ProtonHandler.java:231)
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.inputBuffer(AMQPConnectionContext.java:156)
	at org.apache.activemq.artemis.protocol.amqp.broker.ActiveMQProtonRemotingConnection.bufferReceived(ActiveMQProtonRemotingConnection.java:147)
	at org.apache.activemq.artemis.integration.amqp.ProtonClientConnectionManager.bufferReceived(ProtonClientConnectionManager.java:105)
	at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1407)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
   Locked ownable synchronizers:
	- None
````
Thread owning the lock:
````
"Thread-26 (ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$5@609db43b)" - Thread t@74
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.putVal(HashMap.java:664)
	at java.util.HashMap.put(HashMap.java:612)
	at org.apache.qpid.proton.engine.impl.TransportSession.addUnsettledOutgoing(TransportSession.java:425)
	at org.apache.qpid.proton.engine.impl.TransportImpl.processTransportWorkSender(TransportImpl.java:579)
	at org.apache.qpid.proton.engine.impl.TransportImpl.processTransportWork(TransportImpl.java:518)
	at org.apache.qpid.proton.engine.impl.TransportImpl.writeInto(TransportImpl.java:347)
	at org.apache.qpid.proton.engine.impl.TransportOutputAdaptor.pending(TransportOutputAdaptor.java:59)
	at org.apache.qpid.proton.engine.impl.SaslImpl$SwitchingSaslTransportWrapper.pending(SaslImpl.java:815)
	at org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.pending(HandshakeSniffingTransportWrapper.java:138)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1526)
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.flushBytes(ProtonHandler.java:203)
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.onTransport(AMQPConnectionContext.java:345)
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.Events.dispatch(Events.java:89)
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.dispatch(ProtonHandler.java:485)
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.flush(ProtonHandler.java:298)
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.flush(AMQPConnectionContext.java:184)
	at org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerSenderContext.deliverMessage(ProtonServerSenderContext.java:724)
	at org.apache.activemq.artemis.protocol.amqp.broker.AMQPSessionCallback.sendMessage(AMQPSessionCallback.java:643)
	at org.apache.activemq.artemis.core.server.impl.ServerConsumerImpl.deliverStandardMessage(ServerConsumerImpl.java:1106)
	at org.apache.activemq.artemis.core.server.impl.ServerConsumerImpl.proceedDeliver(ServerConsumerImpl.java:464)
	at org.apache.activemq.artemis.core.server.impl.QueueImpl.proceedDeliver(QueueImpl.java:2934)
	at org.apache.activemq.artemis.core.server.impl.QueueImpl.deliver(QueueImpl.java:2402)
	at org.apache.activemq.artemis.core.server.impl.QueueImpl.access$2000(QueueImpl.java:107)
	at org.apache.activemq.artemis.core.server.impl.QueueImpl$DeliverRunner.run(QueueImpl.java:3207)
	- locked <2c0152eb> (a org.apache.activemq.artemis.core.server.impl.QueueImpl$DeliverRunner)
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42)
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31)
	at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:66)
	at org.apache.activemq.artemis.utils.actors.ProcessorBase$$Lambda$7/302977067.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
   Locked ownable synchronizers:
	- locked <49b63b22> (a java.util.concurrent.ThreadPoolExecutor$Worker)
	- locked <6d7b6705> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
````

**Comment by rgodfrey** [comment]
So, the stack traces show contention between reading incoming messages and sending outgoing messages.  As we've discussed before, changing the configuration here so that we separate the ingress and egress of messages into two separate connections *should* help.

**Comment by grs** [comment]
See https://github.com/EnMasseProject/enmasse/pull/1438 for a possible improvement. (One test appears to be failing which I will try and debug)

**Comment by lulf** [comment]
Uses dedicated connections now
