### ISSUE TITLE
System-tests: Aug list of disabled tests

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1492]
1. io.enmasse.systemtest.standard.mqtt.PublishTest#testPublishQoS2
  - bug: (QoS2 isn't implemented)
  - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/PublishTest.java#L55
  - QoS2 is just for ensuring that messages are delivered exactly once? --where is this being tested in this test?

=======

2. io.enmasse.systemtest.standard.QueueTest#testScaledown
  - bug: #851 #1134
  - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L175
  -  failing, 14:03:19,948 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {} io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.37.144.50:8443/apis/apps/v1beta1/namespaces/standard-shared-0/statefulsets/scalequeue. Message:statefulsets.apps "scalequeue" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=apps, kind=statefulsets, name=scalequeue, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=statefulsets.apps "scalequeue" not found, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

  - are ulfs comments in https://github.com/EnMasseProject/enmasse/issues/851 still valid? can we go ahead and change the test as he suggests, or no for some reason?

=======

3.  io.enmasse.systemtest.standard.TopicTest#testTopicWildcards -not supported now,, something was changed 
  - bug: #105 (probably)
  - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L209
  -  15:14:58,262 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Receiver - Receiver link 'topic/#' opened, granting credits 15:14:58,263 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.ClientHandlerBase - Link closed with Error{condition=amqp:not-found, description='Node not found', info=null}	15:14:58,434 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Sender - Sender link 'topic/No1' opened, sending messages 15:14:58,592 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Sender - Sender link 'topic/No2' opened, sending messages 15:14:58,610 [main] INFO io.enmasse.systemtest.bases.TestBaseWithShared - test failed: io.enmasse.systemtest.standard.TopicTest.testTopicWildcards	testTopicWildcards  Time elapsed: 535.934 sec  <<< ERROR! java.util.concurrent.ExecutionException: java.lang.RuntimeException: Node not found	at io.enmasse.systemtest.standard.TopicTest.testTopicWildcards(TopicTest.java:263)	Caused by: java.lang.RuntimeException: Node not found

=========

4. io.enmasse.systemtest.standard.TopicTest#testDurableLinkRoutedSubscription
  - bug: (if I remember correctly TopicTests were disabled due to some issue with sending mqtt messages)
  - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L230 
  -  15:26:38,014 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {}	io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.37.144.50:8443/apis/apps/v1beta1/namespaces/standard-shared-0/statefulsets/lrtopic. Message: statefulsets.apps "lrtopic" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=apps, kind=statefulsets, name=lrtopic, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=statefulsets.apps "lrtopic" not found, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

=======

5. io.enmasse.systemtest.standard.TopicTest#testDurableMessageRoutedSubscription
  - bug: (if I remember correctly TopicTests were disabled due to some issue with sending mqtt messages)
  - code: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java#L273
  - [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {}
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.37.144.50:8443/apis/apps/v1beta1/namespaces/standard-shared-0/statefulsets/mrtopic. Message: statefulsets.apps "mrtopic" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=apps, kind=statefulsets, name=mrtopic, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=statefulsets.apps "mrtopic" not found, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={})

======

6. io.enmasse.systemtest.brokered.SmokeTest#testCreateAlreadyExistingAddress  ---not supported, something was changed
  - build success seems to be intermittent, sometimes failing, sometimes passing. Further investigation required

======

7. io.enmasse.systemtest.brokered.TopicTest.test#TopicPubSubWildcards
  - bug: #590 
  - code enmasse/systemtests/src/test/java/io/enmasse/systemtest/brokered/TopicTest.java Line 21 
  - observed that test seems to fail on getting address spaces

======

8. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testClientsMetrics
  - bug: #649   
  - not supported with brokered address spaces

9. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testSortConnectionsByContainerId 
  - not supp. with brokered addr spaces
  - bug: #634

10. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testFilterConnectionsByContainerId 
  - not supported with brokered addr spaces
 - bug #634 

11. io.enmasse.systemtest.standard.web.FirefoxWebconsoleTest#testViewConnections 
  - awaiting fix ( gsim is aware ) 
  - bug #818 

12.  io.enmasse.systemtest.standard.web.FirefoxWebconsoleTest#testViewAddressesWildcards
  - not supported 
  - bug #819 

======

13. https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L189
  - bug #903 
  
======

14. https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/PlansTest.java#L43 
  - bug #904 
  - seems to get stuck in 10-15 minute loop of 	
`/standard-shared-0/addresses; 
	13:15:34,063 [main] INFO io.enmasse.systemtest.TestUtils - Checking {name=weak-queue-0, address=weak-queue-0} for ready state
	13:15:39,064 [main] INFO io.enmasse.systemtest.apiclients.AddressApiClient - GET-addresses: path /apis/enmasse.io/v1alpha1/namespaces/myproject/addressspaces/standard-shared-0/addresses; `
then fails ...

======

15. ./src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java:63 
  - bug #669 
```./src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java:63:    @Disabled("disabled due to #669") ```
``` ./src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java-64-    public void testFilterConnectionsByEncrypted() throws Exception { ```
  - not supported with brokered addr space. ( brokered wont give info about encryption details )
  - ``` java.lang.AssertionError: Console failed, does not contain 5 connections
	Expected: is <5>	\n     but: was <0>```

======

16. ./src/test/java/io/enmasse/systemtest/brokered/clients/openwire/MsgPatternsTest.java-53
  - failing because OpenWire doesnt have the correct permissions to create new queues
  - Failed tests:  MsgPatternsTest.testTopicSubscribe:33->ClientTestBase.doTopicSubscribeTest:182 Multiple Failures (2 failures)Producer failed, expected return code 0 ==> expected: <true> but was: <false>Expected 10 sent messages ==> expected: <10> but was: <0>
  - bug #660 
  
======

17. ./src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java-81
  - shows 'dummy' user in certain view
  - bug #667 
  - failing :  FirefoxWebConsoleTest.testFilterConnectionsByUser:80-WebConsoleTest.doTestFilterConnectionsByUser:316 Console failed, does not contain 10 connections Expected: is <10>	     but: was <0>

======

18. ./src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java:409: 
  - issue #1136   (kornys nevi)
``` 	14:03:55,208 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {}
	java.lang.RuntimeException: Only '0' out of '2' in state 'Running' before timeout 
	at io.enmasse.systemtest.TestUtils.waitForNReplicas(TestUtils.java:133) 
```

======

19. src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogApiTest.java
  -  line 155 //!TODO there are missing steps what should happen when required parameter is missing 
  - bug #1215 

20. src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogApiTest.java
  -  line 145  //!TODO there are missing steps what should happen when instanceId already exists 
  - bug #1216 

======

21. systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
``` 14:30:07,292 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {}
	org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	Client does not fail ==> expected: <false> but was: <true>
	Client does not fail ==> expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:79)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:45)
```
  - issue: "test disabled as per-address limit enforcement has been removed" ; test will be enabled once required functionality will be back

======

22. https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/marathon/PlansMarathonTest.java#L42  
  - bug #1306 
  - bug #1309 

======

23. enmasse/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java 264 and 216
  - intermittent build success, still investigating various file sizes and amounts, not sure of the maximum size allowed to transfer ( we were testing ~1gb with broker )
  - bug #1330 
  - https://github.com/EnMasseProject/enmasse/blob/5ffe5199d1cc74cd080734b2f57217aefa9176e7/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L264
tried with messages up to 150mb ( 1x150mb, 15x10mb, 150x1mb) ...tests shows output eg:
javax.jms.JMSException: Delivery failed: released by receiver
	at org.apache.qpid.jms.provider.amqp.AmqpFixedProducer.processDeliveryUpdates(AmqpFixedProducer.java:248)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.processUpdates(AmqpProvider.java:1021)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider.access$1900(AmqpProvider.java:106)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$17.run(AmqpProvider.java:856)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
but the test build is succesful. (?)
  - https://github.com/EnMasseProject/enmasse/blob/5ffe5199d1cc74cd080734b2f57217aefa9176e7/systemtests/src/test/java/io/enmasse/systemtest/brokered/QueueTest.java#L216

brokered test output:
13:05:11,073 [main] INFO io.enmasse.systemtest.bases.TestBase - 100MB non-durable message sent
javax.jms.JMSException: Transport connection remotely closed.
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.pull(JmsConnection.java:913)
	at org.apache.qpid.jms.JmsConnection.pull(JmsConnection.java:897)
	at org.apache.qpid.jms.JmsMessageConsumer.performPullIfRequired(JmsMessageConsumer.java:698)
	at org.apache.qpid.jms.JmsMessageConsumer.dequeue(JmsMessageConsumer.java:317)
	at org.apache.qpid.jms.JmsMessageConsumer.receive(JmsMessageConsumer.java:198)
	at io.enmasse.systemtest.JmsProvider.lambda$receiveMessages$5(JmsProvider.java:189)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at io.enmasse.systemtest.JmsProvider.receiveMessages(JmsProvider.java:187)
	at io.enmasse.systemtest.bases.TestBase.sendReceiveLargeMessage(TestBase.java:1030)
	at io.enmasse.systemtest.bases.TestBase.sendReceiveLargeMessage(TestBase.java:1013)
	at io.enmasse.systemtest.brokered.QueueTest.testLargeMessages(QueueTest.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException: Transport connection remotely closed.
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$20.run(AmqpProvider.java:925)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
...build failure.

**Comment by RH-sdavey** [comment]
#1611 has been created
