### ISSUE TITLE
Connections to the MQTT gateway occasionally fail with CONNACK return code 3

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1503]
Sometimes connections client connections to the MQTT gateway fail.  The client receives a `CONNACK` containing return code `3`. When this happens, the following error is logged by the MQTT gateway:

```
18:41:04.255 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:87)
	at enmasse.mqtt.AmqpBridge.lambda$null$4(AmqpBridge.java:210)
	at enmasse.mqtt.endpoints.AmqpReceiverEndpoint.handleSession(AmqpReceiverEndpoint.java:203)
	at enmasse.mqtt.endpoints.AmqpReceiverEndpoint.messageHandler(AmqpReceiverEndpoint.java:118)
	at io.vertx.proton.impl.ProtonReceiverImpl.onDelivery(ProtonReceiverImpl.java:183)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:158)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:384)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by k-wall** [comment]
This is a coding issue within the MQTT gateway.  I think the `connectionFuture` is being completed twice which violates the API.   The code should be re-expressed probably using future compose.

**Comment by k-wall** [comment]
The analysis above was duff.

The issue occurs when using clientSession false and the client reconnects using the same client-id.  If the disconnect of the previous session is not received by the gateway before the new session arrival is processed, the response to the subscription `list` command goes to the handler of the original session rather than the handler of the new one.  The original handler tries to recomplete the `connectionFuture` future, causing the exception.  Meanwhile the new connection attempt times out, because it has not received a response.  The MQTT client's new connection attempt ends with a `3` being returned.  

If the client tries to connect again, he'll probably be okay, as the original session close will probably have been processed.

This problem points to a design flaw.  The response path uses a fixed name `mqtt.to.<clientid>.control` so previous incarnations of the client may still have an active receiving link.    A redesign should also consider the client-id exclusivity requirement of the MQTT specification.
