### ISSUE TITLE
UserAPI: Fix error messages in response from userapi

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1569]
I'm not able to create user via restapi and crd. 

restapi:
```
20:10:08,228 [main] INFO io.enmasse.systemtest.apiclients.UserApiClient - POST-user: path /apis/user.enmasse.io/v1alpha1/namespaces/brokered-shared-0/messagingusers; body {"metadata":{"name":"brokered-shared-0.test","namespace":"brokered-shared-0"},"spec":{"username":"test","authentication":{"type":"password","password":"test"},"authorization":[{"addresses":["*"],"operations":["send","recv","view"]},{"addresses":[],"operations":["manage"]}]}}
20:10:09,845 [vert.x-eventloop-thread-0] ERROR io.enmasse.systemtest.apiclients.ApiClient - expected-code: 201, response-code: 500, body: null
java.lang.RuntimeException: Status 500 body: null
	at io.enmasse.systemtest.apiclients.ApiClient.responseHandler(ApiClient.java:70)
	at io.enmasse.systemtest.apiclients.UserApiClient.lambda$null$0(UserApiClient.java:102)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

cdr:
```
1,enmasse $ oc get addressspace
NAME                AGE
brokered-shared-0   5m
0,enmasse $ cat user.yaml
apiVersion: user.enmasse.io/v1alpha1
kind: MessagingUser
metadata:
    name: brokered-shared-0.test
spec:
    authentication:
      type: password
      password: test
    authorization:
    - addresses: [ "topic1", "topic2", "*" ]
      operations: [ "send", "recv", "view" ]
0,enmasse $ oc create -f user.yaml
Error from server (InternalError): error when creating "user.yaml": an error on the server ("") has prevented the request from succeeding (post messagingusers.user.enmasse.io)
```

api-server log:
```
2018-08-31 06:19:09 INFO HTTPServer:100 - Request POST /apis/user.enmasse.io/v1alpha1/namespaces/myproject/messagingusers 

2018-08-31 06:19:09 ERROR HttpUserService:40 - Error creating user brokered-shared-0.test 

javax.ws.rs.NotFoundException: HTTP 404 Not Found 

at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:218) 

at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:189) 

at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60) 

at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:107) 

at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) 

at com.sun.proxy.$Proxy45.search(Unknown Source) 

at io.enmasse.user.keycloak.KeycloakUserApi.lambda$createUser$2(KeycloakUserApi.java:106) 

at io.enmasse.user.keycloak.KeycloakUserApi.withKeycloak(KeycloakUserApi.java:67) 

at io.enmasse.user.keycloak.KeycloakUserApi.createUser(KeycloakUserApi.java:102) 

at io.enmasse.api.v1.http.HttpUserService.lambda$createUser$4(HttpUserService.java:112) 

at io.enmasse.api.v1.http.HttpUserService.doRequest(HttpUserService.java:38) 

at io.enmasse.api.v1.http.HttpUserService.createUser(HttpUserService.java:107) 

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 

at java.lang.reflect.Method.invoke(Method.java:498) 

at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) 

at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294) 

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248) 

at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235) 

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398) 

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205) 

at org.jboss.resteasy.plugins.server.vertx.RequestDispatcher.service(RequestDispatcher.java:93) 

at org.jboss.resteasy.plugins.server.vertx.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:65) 

at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:209) 

at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:417) 

at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:482) 

at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:477) 

at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:458) 

at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144) 

at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:712) 

at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:619) 

at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) 

at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) 

at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) 

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 

at java.lang.Thread.run(Thread.java:748) 

2018-08-31 06:19:09 ERROR i18n:72 - RESTEASY019525: Unexpected 

java.lang.IllegalStateException: RESTEASY003765: Response is closed. 

at org.jboss.resteasy.specimpl.BuiltResponse.abortIfClosed(BuiltResponse.java:257) 

at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.abortIfClosed(ClientResponse.java:325) 

at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.getEntity(ClientResponse.java:74) 

at org.jboss.resteasy.core.ExceptionHandler.unwrapException(ExceptionHandler.java:128) 

at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) 

at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222) 

at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:171) 

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:414) 

at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205) 

at org.jboss.resteasy.plugins.server.vertx.RequestDispatcher.service(RequestDispatcher.java:93) 

at org.jboss.resteasy.plugins.server.vertx.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:65) 

at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:209) 

at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:417) 

at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:482) 

at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:477) 

at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:458) 

at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144) 

at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:712) 

at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:619) 

at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) 

at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) 

at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) 

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 

at java.lang.Thread.run(Thread.java:748)
```

**Comment by lulf** [comment]
Field .spec.username is missing. But keep issue open to fix bad error message

**Comment by kornys** [comment]
@lulf ah I see, I will try it, anyway I followed desight doc for userApi for crd.

**Comment by lulf** [comment]
@kornys Any other bad error messages?

**Comment by kornys** [comment]
@lulf nope, but keep it open, I will start with writing UserApi specific tests and we will see if all error messages are ok.

**Comment by kornys** [comment]
@lulf so I found another wrong response, I send payload with wrong metadata name like ".username" and response is same like for wrong group.

```
14:43:50,756 [main] INFO io.enmasse.systemtest.apiclients.UserApiClient - POST-user: path /apis/user.enmasse.io/v1alpha1/namespaces/myproject/messagingusers; body {"metadata":{"name":".pepaNaTestovani"},"spec":{"username":"pepaNaTestovani","authentication":{"type":"password","password":"cGVwYU5hVGVzdG92YW5p"},"authorization":[{"addresses":["jenda"],"operations":["send","recv","posilani"]}]}}
java.lang.RuntimeException: {"apiVersion":"v1","kind":"Status","status":"Failure","code":500,"reason":"Internal Server Error","message":"Cannot deserialize value of type `io.enmasse.user.model.v1.Operation` from String \"posilani\": value not one of declared Enum instance names: [send, view, recv, manage]\n at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 217] (through reference chain: io.enmasse.user.model.v1.User[\"spec\"]->io.enmasse.user.model.v1.UserSpec[\"authorization\"]->java.util.ArrayList[0]->io.enmasse.user.model.v1.UserAuthorization[\"operations\"]->java.util.ArrayList[2])"}
```
