### ISSUE TITLE
UserApi: server response 500: Conflict when trying to create same user in same realm

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1575]
I understand why it returns this responce (because user is already created), but how can I update users authz groups?

```
17:53:36,706 [main] INFO io.enmasse.systemtest.apiclients.UserApiClient - POST-user: path /apis/user.enmasse.io/v1alpha1/namespaces/myproject/messagingusers; body {"metadata":{"name":"brokered-shared-4.test"},"spec":{"username":"test","authentication":{"type":"password","password":"dGVzdA=="},"authorization":[{"addresses":["*"],"operations":["send","recv","view"]},{"addresses":[],"operations":["manage"]}]}}
17:53:37,994 [vert.x-eventloop-thread-0] ERROR io.enmasse.systemtest.apiclients.ApiClient - expected-code: 201, response-code: 500, body: {"apiVersion":"v1","kind":"Status","status":"Failure","code":500,"reason":"Internal Server Error","message":"Conflict"}
java.lang.RuntimeException: Status 500 body: {"apiVersion":"v1","kind":"Status","status":"Failure","code":500,"reason":"Internal Server Error","message":"Conflict"}
	at io.enmasse.systemtest.apiclients.ApiClient.responseHandler(ApiClient.java:70)
	at io.enmasse.systemtest.apiclients.UserApiClient.lambda$null$0(UserApiClient.java:73)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lulf** [comment]
Currently need to delete and create. However we should perhaps implement PUT on a user to do this

**Comment by kornys** [comment]
I see I think it is not a good solution re-creating users, so yeah PUt seems to me is the best 👍 for now I will update systemtests to check if user is created instead of try to create user test before every test with shared address space

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1563
