### ISSUE TITLE
Make "caCertSecretName" optional in external authService config

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1580]
When using an address space configuration with an external authentication service with a host for which there is a proper (not self-signed) certificate, it would be good to have the "caCertSecretName" configuration be optional. Meaning that in this case JRE / OS provided CA certs should be used for validation.

Currently, when omitting the "caCertSecretName" property, there is an exception about this property being required.
With an empty property value, there is an internal exception later on:
````
2018-09-04 07:34:31 INFO  ControllerChain:109 - Check address spaces: [play:bosch, play:pg-hub-4463]
2018-09-04 07:34:31 WARN  ResourceChecker:53 - Exception in checker task
java.lang.IllegalArgumentException: Name must be provided.
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:255)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:70)
	at io.enmasse.controller.common.KubernetesHelper.getSecret(KubernetesHelper.java:220)
	at io.enmasse.controller.TemplateInfraResourceFactory.lambda$createResourceList$1(TemplateInfraResourceFactory.java:51)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:51)
	at io.enmasse.controller.StatusController.isReady(StatusController.java:38)
	at io.enmasse.controller.StatusController.handle(StatusController.java:26)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:120)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by calohmn** [comment]
(first PR for this was #1584)

**Comment by lulf** [comment]
@calohmn I think the fix should work for your case. If you have a chance to test it, let me know if it works.

**Comment by calohmn** [comment]
@lulf thanks, I can test this tomorrow. Do you want to include it in the 0.23.0 release then?

**Comment by lulf** [comment]
@calohmn yes

**Comment by calohmn** [comment]
@lulf test was successful, it works :thumbsup:
