### ISSUE TITLE
System-tests: Sep list of disabled tests

### ISSUE THREAD

**Issue by RH-sdavey** [EnMasseProject/enmasse#1611]
1. io.enmasse.systemtest.brokered.SmokeTest#testCreateAlreadyExistingAddress
    - @Disabled("disabled until #346 will be fixed")  #346 is closed
    - not supported, something was changed
    - build success seems to be intermittent, sometimes failing, sometimes passing. Further investigation required

2. io.enmasse.systemtest.brokered.TopicTest#testTopicPubSubWildcards
    - @Disabled("disable due to authorization exception with create queue on topic address with wildcards")
    - bug: #590 
    - code enmasse/systemtests/src/test/java/io/enmasse/systemtest/brokered/TopicTest.java Line 21 
    - observed that test seems to fail on getting address spaces

3. io.enmasse.systemtest.brokered.web.FirefoxWebConsoleTest#testFilterConnectionsByEncrypted
    -  not supported with brokered addr space. ( brokered wont give info about encryption details )
    -  ` java.lang.AssertionError: Console failed, does not contain 5 connections
	Expected: is <5>	\n     but: was <0> `

4. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testFilterConnectionsByContainerId 
    - not supported with brokered addr spaces
    - bug #634  

5. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testSortConnectionsByContainerId 
    - not supp. with brokered addr spaces
    - bug: #634

6. io.enmasse.systemtest.brokered.web.FirefoxWebconsoleTest#testClientsMetrics
    - bug: #649   
    - not supported with brokered address spaces

7. io.enmasse.systemtest.standard.web.FirefoxWebconsoleTest#testViewAddressesWildcards
    - not supported 
    - bug #819 

8. io.enmasse.systemtest.standard.mqtt.PublishTest#testPublishQoS2
    - bug: (QoS2 isn't implemented)

9. io.enmasse.systemtest.standard.mqtt.PublishTest#testRetainedMessages
    - @Disabled("related issue: #1529")

10. io.enmasse.systemtest.standard.QueueTest#testScaledown
    - @Disabled("disabled due to issue #851") bug: #851 #1134
    -  failing, 14:03:19,948 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {} io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.37.144.50:8443/apis/apps/v1beta1/namespaces/standard-shared-0/statefulsets/scalequeue. Message:statefulsets.apps "scalequeue" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=apps, kind=statefulsets, name=scalequeue, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=statefulsets.apps "scalequeue" not found, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

11. io.enmasse.systemtest.standard.PlansTest#testAppendAddressPlan
    - @Disabled("test disabled because feature for appending address-plan is not implemented yet, issue: #904")

12. io.enmasse.systemtest.standard.clients.rhea.MsgPatternsTest#testMessageSelectorQueue
    - @Disabled("selectors for queue does not work")
 
13. io.enmasse.systemtest.standard.TopicTest#testTopicWildcards
    - @Disabled("topic wildcards are not supported")
    - not supported now,, something was changed 
    - bug: #105 (probably)
    - ` 15:14:58,262 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Receiver - Receiver link 'topic/#' opened, granting credits 15:14:58,263 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.ClientHandlerBase - Link closed with Error{condition=amqp:not-found, description='Node not found', info=null}	15:14:58,434 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Sender - Sender link 'topic/No1' opened, sending messages 15:14:58,592 [vert.x-eventloop-thread-0] INFO io.enmasse.systemtest.amqp.Sender - Sender link 'topic/No2' opened, sending messages 15:14:58,610 [main] INFO io.enmasse.systemtest.bases.TestBaseWithShared - test failed: io.enmasse.systemtest.standard.TopicTest.testTopicWildcards	testTopicWildcards  Time elapsed: 535.934 sec  <<< ERROR! java.util.concurrent.ExecutionException: java.lang.RuntimeException: Node not found	at io.enmasse.systemtest.standard.TopicTest.testTopicWildcards(TopicTest.java:263)	Caused by: java.lang.RuntimeException: Node not found 
`

14. io.enmasse.systemtest.standard.TopicTest#testDurableLinkRoutedSubscription
    - @Disabled("durable subscriptions are not supported")
    - bug: (if I remember correctly TopicTests were disabled due to some issue with sending mqtt messages)
     -  15:26:38,014 [main] ERROR io.enmasse.systemtest.ability.ITestSeparator - Caught exception {}	io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.37.144.50:8443/apis/apps/v1beta1/namespaces/standard-shared-0/statefulsets/lrtopic. Message: statefulsets.apps "lrtopic" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=apps, kind=statefulsets, name=lrtopic, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=statefulsets.apps "lrtopic" not found, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

15. io.enmasse.systemtest.standard.TopicTest#testDurableMessageRoutedSubscription
    - @Disabled("durable subscriptions are not supported")
    - as above

16. io.enmasse.systemtest.standard.web.FirefoxWebConsoleTest#testAddressNameWithHyphens
    - @Disabled("disabled due to #1601")
    - Error in console/ agent when creating addresses with "-" symbol as 61st character of the name

17. io.enmasse.systemtest.standard.web.FirefoxWebConsoleTest#testCreateAddressWithSpecialChars
    - @Disabled("disabled due to #1601")
    - as above

18.  All src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java tests 
     - @Disabled("Only few chrome tests are enabled, rest functionality is covered by firefox")

19.  All src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java tests 
     - @Disabled("Only few chrome tests are enabled, rest functionality is covered by firefox")

20. io.enmasse.systemtest.marathon.PlansMarathonTest#testHighLoadAddresses
    - @Disabled("disabled due to: #1319")

21. io.enmasse.systemtest.marathon.PlansMarathonTest#testHighLoadAddressesInBatches
    -  @Disabled("disabled due to: #1306")

22. io.enmasse.systemtest.common.plans.PlansTest#testGlobalSizeLimitations
    - @Disabled("test disabled as per-address limit enforcement has been removed")

23. io.enmasse.systemtest.common.plans.PlansTest#testMessagePersistenceAfterAutoScale
    - @Disabled("test disabled due to issue: #1134")

24. io.enmasse.systemtest.common.plans.PlansTest#testMessagePersistenceAfterChangePlan
    - @Disabled("test disabled due to issue: #1136")

25. io.enmasse.systemtest.common.catalog.ServiceCatalogApiTest#testProvideServicesWithIdenticalId
    - @Disabled("disabled due to issue: #1216")
    - //!TODO there are missing steps what should happen when instanceId already exists

26. io.enmasse.systemtest.common.catalog.ServiceCatalogApiTest#testMissingRequiredParameter
    - @Disabled("disabled due to issue: #1215")
    - //!TODO there are missing steps what should happen when required parameter is missing

27.  io.enmasse.systemtest.standard.QueueTest#testLargeMessages
     - @Disabled("due to issue #1330")
     - See below

28. io.enmasse.systemtest.brokered.QueueTest#testLargeMessages
    - @Disabled("due to issue #1330")
    - intermittent build success, still investigating various file sizes and amounts, not sure of the maximum size allowed to transfer ( we were testing ~1gb with broker )
    - bug #1330 
    - 
```
brokered test output:
13:05:11,073 [main] INFO io.enmasse.systemtest.bases.TestBase - 100MB non-durable message sent
javax.jms.JMSException: Transport connection remotely closed.
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.pull(JmsConnection.java:913)
	at org.apache.qpid.jms.JmsConnection.pull(JmsConnection.java:897)
	at org.apache.qpid.jms.JmsMessageConsumer.performPullIfRequired(JmsMessageConsumer.java:698)
	at org.apache.qpid.jms.JmsMessageConsumer.dequeue(JmsMessageConsumer.java:317)
	at org.apache.qpid.jms.JmsMessageConsumer.receive(JmsMessageConsumer.java:198)
	at io.enmasse.systemtest.JmsProvider.lambda$receiveMessages$5(JmsProvider.java:189)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at io.enmasse.systemtest.JmsProvider.receiveMessages(JmsProvider.java:187)
	at io.enmasse.systemtest.bases.TestBase.sendReceiveLargeMessage(TestBase.java:1030)
	at io.enmasse.systemtest.bases.TestBase.sendReceiveLargeMessage(TestBase.java:1013)
	at io.enmasse.systemtest.brokered.QueueTest.testLargeMessages(QueueTest.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.io.IOException: Transport connection remotely closed.
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$20.run(AmqpProvider.java:925)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by RH-sdavey** [comment]
#1492 will be closed, all currently disabled tests are listed here.
