### ISSUE TITLE
Connectivity to the peer container was lost reported when forming receiving link to durable sub

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#1691]
**Describe the bug**

The following sequence of address creation leads to an error being received on attach at the subscriber and an exception reported to the broker's pod log. I am testing on master (efa9751e17640e46cf4dfa2f693de7e8954c079a)

**To Reproduce**

1. Create a standard address space
2. Create a pooled topic (but don't yet create a subscriber)
3. Send messages to the pooled topic.  I am using proton cpp example simple_send
4. Create a durable subscription associated with the topic
5. Attach receiver the durable subscription.  I am using proton cpp example simple_recv.

I expect the the receiver should be successfully attached and should not see the messages sent at step 3.

Instead I see:

`[0x7fdf914086e0]:0 <- @attach(18) [name="6fce4944-6ffc-4f49-a401-060ca6e8345e", handle=0, role=false, snd-settle-mode=2, rcv-settle-mode=0, target=@target(41) [durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x7fdf914086e0]:0 <- @detach(22) [handle=0, closed=true, error=@error(29) [condition=:"qd:routed-link-lost", description="Connectivity to the peer container was lost"]]`

Checking the broker's pod log, I see the following:

`2018-09-25 21:51:13,150 WARN  [org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler] Incorrect Routing Type for queue, expecting: ANYCAST: java.lang.IllegalStateException: Incorrect Routing Type for queue, expecting: ANYCAST
	at org.apache.activemq.artemis.protocol.amqp.broker.AMQPSessionCallback.queueQuery(AMQPSessionCallback.java:302) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerSenderContext.getMatchingQueue(ProtonServerSenderContext.java:440) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerSenderContext.initialise(ProtonServerSenderContext.java:388) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPSessionContext.addSender(AMQPSessionContext.java:168) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.remoteLinkOpened(AMQPConnectionContext.java:243) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.onRemoteOpen(AMQPConnectionContext.java:459) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.Events.dispatch(Events.java:68) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.dispatch(ProtonHandler.java:485) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.flush(ProtonHandler.java:298) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.inputBuffer(ProtonHandler.java:263) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.inputBuffer(AMQPConnectionContext.java:158) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.protocol.amqp.broker.ActiveMQProtonRemotingConnection.bufferReceived(ActiveMQProtonRemotingConnection.java:147) [artemis-amqp-protocol-2.6.2.jar:]
	at org.apache.activemq.artemis.integration.amqp.ProtonClientConnectionManager.bufferReceived(ProtonClientConnectionManager.java:105) [amqp-connector-0.23-SNAPSHOT.jar:]
	at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:73) [artemis-core-client-2.6.2.jar:2.6.2]
`

**Comment by grs** [comment]
This is a result of https://issues.apache.org/jira/browse/ARTEMIS-2100
