### ISSUE TITLE
AddressSpace creation: Check whether "infra-uuid" has been set

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1707]
## why

We create address spaces by adding the corresponding Config Maps.
Having migrated from EnMasse < 0.23.0 and forgotten to set the `enmasse.io/infra-uuid` annotation in the address space yml, there is only this mysterious exception in the address space controller log:
````
2018-09-28 09:40:26.988 [Thread-4] WARN  ResourceChecker:53 - Exception in checker task
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:205)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:157)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
	at io.enmasse.controller.common.KubernetesHelper.processTemplate(KubernetesHelper.java:61)
	at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:101)
	at io.enmasse.controller.CreateController.handle(CreateController.java:109)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:122)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
````
(updating to the upcoming 3.1.13 version of kubernetes-client will show the name of the missing INFRA_UUID attribute - see [kubernetes-client#1165](https://github.com/fabric8io/kubernetes-client/issues/1165)).
It would be good to add extra validation of the address space here and throw a more specific error.

## Proposal

Add validation logic checking for the `enmasse.io/infra-uuid` annotation in AddressSpaceV1Deserializer / AddressSpace.Builder (so that also `ConfigMapAddressSpaceApi.getAddressSpaceFromConfig()` is covered).

**Comment by lulf** [comment]
Fixed by https://github.com/EnMasseProject/enmasse/pull/1776
