### ISSUE TITLE
Add extra log output / error handling to address space certificate creation

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#1754]
We just got the following error when creating an address space ("pg-hub-4795"):
````
2018-10-08 14:37:08 INFO  CreateController:118 - Creating address space {name=pg-hub-4795,namespace=play,type=standard,plan=unlimited-standard-without-mqtt,endpoints=[{name=messaging,host=messaging-pg-hub-4795-enmasse.something.com,service=messaging,servicePort=amqps,cert={provider=selfsigned,secretNameexternal-certs-messaging-tqc344k3yh}}, {name=amqp-wss,host=amqp-wss-pg-hub-4795-enmasse.something.com,service=messaging,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-messaging-tqc344k3yh}}, {name=mqtt,host=null,service=mqtt,servicePort=secure-mqtt,cert={provider=selfsigned,secretNameexternal-certs-mqtt-tqc344k3yh}}, {name=console,host=console-pg-hub-4795-enmasse.something.com,service=console,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-console-tqc344k3yh}}],status={isReady=false,endpointStatuses=[],messages=[]}}
2018-10-08 14:37:08 INFO  LogEventLogger:25 - AddressSpaceCreated (kind=AddressSpace name=pg-hub-4795): Created address space
2018-10-08 14:37:08 INFO  ControllerChain:120 - Controller StatusController
[GC (Allocation Failure)  121047K->83430K(126464K), 0.0031263 secs]
2018-10-08 14:37:08 INFO  ControllerChain:120 - Controller EndpointController
2018-10-08 14:37:08 INFO  EndpointController:204 - Creating route messaging-tqc344k3yh for endpoint messaging
2018-10-08 14:37:08 INFO  EndpointController:193 - Ca secret route-ca-pg-hub-4795tqc344k3yh for endpoint {name=amqp-wss,host=amqp-wss-pg-hub-4795-enmasse.something.com,service=messaging,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-messaging-tqc344k3yh}} does not yet exist, skipping route creation for now
2018-10-08 14:37:08 INFO  EndpointController:193 - Ca secret route-ca-pg-hub-4795tqc344k3yh for endpoint {name=console,host=console-pg-hub-4795-enmasse.something.com,service=console,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-console-tqc344k3yh}} does not yet exist, skipping route creation for now
2018-10-08 14:37:08 INFO  ControllerChain:120 - Controller AuthController
2018-10-08 14:37:08 INFO  OpenSSLCertManager:74 - Running command '[openssl, req, -new, -days, 11000, -x509, -batch, -nodes, -out, /tmp/tls691078537590150754crt, -keyout, /tmp/tls4016386294910593457key]'
2018-10-08 14:37:08 INFO  LogEventLogger:25 - CertCreated (kind=AddressSpace name=pg-hub-4795): Created address space CA
2018-10-08 14:37:08 INFO  OpenSSLCertManager:74 - Running command '[openssl, req, -new, -batch, -nodes, -keyout, /tmp/admin.tqc344k3yh.tqc344k3yh.key, -subj, /O=io.enmasse/CN=admin.tqc344k3yh, -out, /tmp/admin.tqc344k3yh.tqc344k3yh.csr]'
2018-10-08 14:37:08 WARN  AuthController:129 - Error issuing component certificates
java.lang.NullPointerException
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.enmasse.controller.auth.OpenSSLCertManager.createTempFileFromSecret(OpenSSLCertManager.java:180)
	at io.enmasse.controller.auth.OpenSSLCertManager.signCsr(OpenSSLCertManager.java:138)
	at io.enmasse.controller.auth.AuthController.lambda$issueComponentCertificates$1(AuthController.java:119)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.enmasse.controller.auth.AuthController.issueComponentCertificates(AuthController.java:123)
	at io.enmasse.controller.auth.AuthController.handle(AuthController.java:142)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:122)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
2018-10-08 14:37:08 WARN  LogEventLogger:22 - CertCreateFailed (kind=AddressSpace name=pg-hub-4795): Error creating component certificates: null
2018-10-08 14:37:08 INFO  SelfsignedCertProvider:52 - Creating self-signed certificates for console-tqc344k3yh.enmasse.svc
````

The issue here is, that the created K8s Secret "ca-pg-hub-4795tqc344k3yh" contains the entries "tls.crt" and "tls.key" but each has no value.

Maybe something went wrong during the "openssl" invocation in `OpenSSLCertManager.createSelfSignedCert`?
````
Running command '[openssl, req, -new, -days, 11000, -x509, -batch, -nodes, -out, /tmp/tls691078537590150754crt, -keyout, /tmp/tls4016386294910593457key]'
````
(Unfortunately the pod already got restarted since so I could check whether the "/tmp/tls691078537590150754crt" and "/tmp/tls4016386294910593457key" were there.)

I think adding some sanity checks for cert array length, etc. would help here.

As follow-up exception, this occurred repeatedly:
````
2018-10-08 14:37:09 WARN  AuthController:82 - Error providing certificate for service console hosts [console-tqc344k3yh.amqonline-play.svc]: null
java.lang.NullPointerException
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.enmasse.controller.auth.OpenSSLCertManager.createTempFileFromSecret(OpenSSLCertManager.java:180)
	at io.enmasse.controller.auth.OpenSSLCertManager.signCsr(OpenSSLCertManager.java:138)
	at io.enmasse.controller.auth.SelfsignedCertProvider.provideCert(SelfsignedCertProvider.java:62)
	at io.enmasse.controller.auth.AuthController.issueExternalCertificates(AuthController.java:80)
	at io.enmasse.controller.auth.AuthController.handle(AuthController.java:144)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:122)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by calohmn** [comment]
@k-wall thanks for the fix! With this, next time the underlying cause should hopefully become obvious.
