### ISSUE TITLE
enmasse.broker.forwarder.ForwarderControllerTest > testBrokerReplicator FAILED

### ISSUE THREAD

**Issue by grs** [EnMasseProject/enmasse#200]
> Task :topic-forwarder:test

enmasse.broker.forwarder.ForwarderControllerTest > testBrokerReplicator FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at enmasse.broker.forwarder.ForwarderControllerTest.waitForConnections(ForwarderControllerTest.java:126)
        at enmasse.broker.forwarder.ForwarderControllerTest.testBrokerReplicator(ForwarderControllerTest.java:84)

1 test completed, 1 failed

Possibly due to?:

2017-09-11 15:31:54 ERROR server:81 - AMQ224000: Failure in initialisation
    java.net.BindException: Address already in use

**Comment by lulf** [comment]
Reopen if seen again. The test has been rewritten to use a random port
