### ISSUE TITLE
Console failed after creation address

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2058]
**Describe the bug**
Console shows disconnect error after creating address using web console.

**Reproducer**
- Create address space
- Opens web console
- open address tab
- Create address using wizard

All jobs in Jenkins are affected.
it started failing after https://github.com/EnMasseProject/enmasse/pull/2056 and I saw it was merged without jenkins PR build

agent log
```
{"log":"2018-11-29T16:45:13.127Z agent INFO  GET /oapi/v1/namespaces/enmasse-master-1511/routes/messaging-sg0oenkjer =\u003e 200 \n","stream":"stderr","time":"2018-11-29T16:45:13.128721326Z"}
{"log":"2018-11-29T16:45:13.139Z agent INFO  kc_idp_hint override: \n","stream":"stderr","time":"2018-11-29T16:45:13.139339834Z"}
{"log":"2018-11-29T16:45:13.169Z agent INFO  GET /api/v1/namespaces/enmasse-master-1511/configmaps?labelSelector=type%3Daddress-config%2CinfraUuid%3Dsg0oenkjer =\u003e 200 \n","stream":"stderr","time":"2018-11-29T16:45:13.169202626Z"}
{"log":"2018-11-29T16:45:13.177Z agent INFO  GET /api/v1/watch/namespaces/enmasse-master-1511/configmaps?labelSelector=type%3Daddress-config%2CinfraUuid%3Dsg0oenkjer =\u003e 200 \n","stream":"stderr","time":"2018-11-29T16:45:13.177436162Z"}
{"log":"2018-11-29T16:45:13.234Z agent INFO  [broker.sg0oenkjer-5797f5ccb4-knlds] broker controller ready\n","stream":"stderr","time":"2018-11-29T16:45:13.234914409Z"}
{"log":"2018-11-29T16:45:13.234Z agent INFO  Unable to check broker (broker is defined, addresses is not defined)\n","stream":"stderr","time":"2018-11-29T16:45:13.234947325Z"}
{"log":"2018-11-29T16:45:13.258Z agent INFO  [broker.sg0oenkjer-5797f5ccb4-knlds] ready to send requests\n","stream":"stderr","time":"2018-11-29T16:45:13.258658156Z"}
{"log":"2018-11-29T16:45:13.272Z agent INFO  addresses_defined: initial [\"topic-via-web-0\"]\n","stream":"stderr","time":"2018-11-29T16:45:13.272745308Z"}
{"log":"/opt/app-root/src/lib/metrics.js:52\n","stream":"stderr","time":"2018-11-29T16:45:13.275540621Z"}
{"log":"        var phase = address.status.phase;\n","stream":"stderr","time":"2018-11-29T16:45:13.275553249Z"}
{"log":"                                  ^\n","stream":"stderr","time":"2018-11-29T16:45:13.275556052Z"}
{"log":"\n","stream":"stderr","time":"2018-11-29T16:45:13.275558436Z"}
{"log":"TypeError: Cannot read property 'phase' of undefined\n","stream":"stderr","time":"2018-11-29T16:45:13.275560739Z"}
{"log":"    at Metrics.addresses_defined (/opt/app-root/src/lib/metrics.js:52:35)\n","stream":"stderr","time":"2018-11-29T16:45:13.275563622Z"}
{"log":"    at emitOne (events.js:101:20)\n","stream":"stderr","time":"2018-11-29T16:45:13.27556621Z"}
{"log":"    at AddressSource.emit (events.js:188:7)\n","stream":"stderr","time":"2018-11-29T16:45:13.275568553Z"}
{"log":"    at AddressSource.dispatch (/opt/app-root/src/lib/internal_address_source.js:119:10)\n","stream":"stderr","time":"2018-11-29T16:45:13.275570896Z"}
{"log":"    at AddressSource.updated (/opt/app-root/src/lib/internal_address_source.js:156:14)\n","stream":"stderr","time":"2018-11-29T16:45:13.27557352Z"}
{"log":"    at emitOne (events.js:96:13)\n","stream":"stderr","time":"2018-11-29T16:45:13.275575814Z"}
{"log":"    at Watcher.emit (events.js:188:7)\n","stream":"stderr","time":"2018-11-29T16:45:13.27557809Z"}
{"log":"    at Immediate.\u003canonymous\u003e (/opt/app-root/src/lib/kubernetes.js:167:14)\n","stream":"stderr","time":"2018-11-29T16:45:13.275580342Z"}
{"log":"    at runCallback (timers.js:672:20)\n","stream":"stderr","time":"2018-11-29T16:45:13.275583326Z"}
{"log":"    at tryOnImmediate (timers.js:645:5)\n","stream":"stderr","time":"2018-11-29T16:45:13.275585459Z"}
```

![io enmasse systemtest brokered web firefoxwebconsoletest testcreatedeletequeue_2018-11-29_12 27 15 577](https://user-images.githubusercontent.com/11318335/49247390-74743c80-f417-11e8-88da-650dbbbac446.png)
![io enmasse systemtest brokered web firefoxwebconsoletest testcreatedeletequeue_2018-11-29_12 27 16 084](https://user-images.githubusercontent.com/11318335/49247400-7a6a1d80-f417-11e8-9e97-50184a4a2191.png)
![io enmasse systemtest brokered web firefoxwebconsoletest testcreatedeletequeue_2018-11-29_12 27 16 599](https://user-images.githubusercontent.com/11318335/49247406-7ccc7780-f417-11e8-80db-0a915fc5fd94.png)

**Comment by kornys** [comment]
@lulf no worries :)
