### ISSUE TITLE
[api-model] schema obejct deserialization does not work

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2461]
**Describe the bug**
schema obejct deserialization does not work

**To Reproduce**
1. get schema from api-server
2. try to deserialize json to schema obejct
3. See error

```
2019-03-18T09:13:15.639Z INFO  [AddressApiClient] GET-schema: path /apis/enmasse.io/v1beta1/namespaces/myproject/addressspaceschemas;
2019-03-18T09:13:16.741Z INFO  [AddressSpaceUtils] Got Schema object: {"apiVersion":"enmasse.io/v1beta1","kind":"AddressSpaceSchemaList","metadata":{},"items":[{"apiVersion":"enmasse.io/v1beta1","kind":"AddressSpaceSchema","metadata":{"annotations":{},"creationTimestamp":"2019-03-18T09:13:15.633Z","labels":{},"name":"brokered"},"spec":{"description":"A brokered address space consists of a broker combined with a console for managing addresses.","addressTypes":[{"name":"queue","description":"A queue that supports selectors, message grouping and transactions","plans":[{"name":"brokered-queue","description":"Creates a queue on a broker."}]},{"name":"topic","description":"A topic supports pub-sub semantics. Messages sent to a topic address is forwarded to all subscribes on that address.","plans":[{"name":"brokered-topic","description":"Creates a topic on a broker."}]}],"plans":[{"name":"brokered-single-broker","description":"Single Broker instance"}]}},{"apiVersion":"enmasse.io/v1beta1","kind":"AddressSpaceSchema","metadata":{"annotations":{},"creationTimestamp":"2019-03-18T09:13:15.633Z","labels":{},"name":"standard"},"spec":{"description":"A standard address space consists of an AMQP router network in combination with attachable 'storage units'. The implementation of a storage unit is hidden from the client and the routers with a well defined API.","addressTypes":[{"name":"anycast","description":"A direct messaging address type. Messages sent to an anycast address are not stored but forwarded directly to a consumer.","plans":[{"name":"standard-large-anycast","description":"Creates a large anycast address."},{"name":"standard-medium-anycast","description":"Creates a medium anycast address."},{"name":"standard-small-anycast","description":"Creates a small anycast address."}]},{"name":"multicast","description":"A direct messaging address type. Messages sent to a multicast address are not stored but forwarded directly to multiple consumers.","plans":[{"name":"standard-small-multicast","description":"Creates a small multicast address."},{"name":"standard-large-multicast","description":"Creates a large multicast address."},{"name":"standard-medium-multicast","description":"Creates a medium multicast address."}]},{"name":"queue","description":"A store-and-forward queue. A queue may be sharded across multiple storage units, in which case message ordering is no longer guaranteed.","plans":[{"name":"standard-large-queue","description":"Creates a large queue backed by a dedicated broker."},{"name":"standard-xlarge-queue","description":"Creates an extra large queue backed by 2 brokers."},{"name":"standard-small-queue","description":"Creates a small queue sharing underlying broker with other queues."},{"name":"standard-medium-queue","description":"Creates a medium sized queue sharing underlying broker with other queues."},{"name":"test-schema-rest-api-addr-plan","description":"Custom systemtests defined address plan"}]},{"name":"topic","description":"A topic address for store-and-forward publish-subscribe messaging. Each message published to a topic address is forwarded to all subscribes on that address.","plans":[{"name":"standard-medium-topic","description":"Creates a medium sized topic sharing underlying broker with other topics."},{"name":"standard-large-topic","description":"Creates a large topic backed by a dedicated broker."},{"name":"standard-xlarge-topic","description":"Creates an extra large topic backed by 2 brokers."},{"name":"standard-small-topic","description":"Creates a small topic sharing underlying broker with other topics."}]},{"name":"subscription","description":"A subscription on a topic","plans":[{"name":"standard-small-subscription","description":"Creates a small durable subscription on a topic."},{"name":"standard-large-subscription","description":"Creates a large durable subscription on a topic."},{"name":"standard-medium-subscription","description":"Creates a medium durable subscription on a topic."}]}],"plans":[{"name":"standard-small","description":"Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis"},{"name":"schema-rest-api-plan","description":"Custom systemtests defined address space plan"},{"name":"standard-unlimited","description":"Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis."},{"name":"standard-unlimited-with-mqtt","description":"Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis and MQTT support."},{"name":"standard-medium","description":"Messaging infrastructure based on Apache Qpid Dispatch Router and Apache ActiveMQ Artemis."}]}}]}
2019-03-18T09:13:16.808Z INFO  [ApiClient] DELETE-address-space-plan: path '/apis/admin.enmasse.io/v1beta2/namespaces/myproject/addressspaceplans/schema-rest-api-plan'
2019-03-18T09:13:16.840Z INFO  [ApiClient] DELETE-address-plan: path '/apis/admin.enmasse.io/v1beta2/namespaces/myproject/addressplans/test-schema-rest-api-addr-plan'
2019-03-18T09:13:16.857Z INFO  [TestBase] All addressspaces will be removed
2019-03-18T09:13:16.858Z INFO  [TimeMeasuringSystem] End time of operation TEST_EXECUTION is correctly stored
2019-03-18T09:13:16.864Z ERROR [ITestSeparator] Caught exception
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "apiVersion" (class io.enmasse.address.model.Schema), not marked as ignorable (3 known properties: "authenticationServices", "addressSpaceTypes", "creationTimestamp"])
 at [Source: (String)"{"apiVersion":"enmasse.io/v1beta1","kind":"AddressSpaceSchemaList","metadata":{},"items":[{"apiVersion":"enmasse.io/v1beta1","kind":"AddressSpaceSchema","metadata":{"annotations":{},"creationTimestamp":"2019-03-18T09:13:15.633Z","labels":{},"name":"brokered"},"spec":{"description":"A brokered address space consists of a broker combined with a console for managing addresses.","addressTypes":[{"name":"queue","description":"A queue that supports selectors, message grouping and transactions","plans""[truncated 4090 chars]; line: 1, column: 16] (through reference chain: io.enmasse.address.model.Schema["apiVersion"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.8.jar:2.9.8]
	at io.enmasse.systemtest.utils.AddressSpaceUtils.getSchema(AddressSpaceUtils.java:350) ~[classes/:na]
	at io.enmasse.systemtest.bases.TestBase.getSchema(TestBase.java:486) ~[test-classes/:na]
	at io.enmasse.systemtest.common.api.ApiServerTest.testRestApiGetSchema(ApiServerTest.java:86) ~[test-classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628) ~[junit-platform-commons-1.4.0.jar:1.4.0]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117) ~[junit-jupiter-engine-5.4.0.jar:5.4.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184) ~[junit-jupiter-engine-5.4.0.jar:5.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180) ~[junit-jupiter-engine-5.4.0.jar:5.4.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127) ~[junit-jupiter-engine-5.4.0.jar:5.4.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68) ~[junit-jupiter-engine-5.4.0.jar:5.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.4.0.jar:1.4.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229) ~[junit-platform-launcher-1.4.0.jar:1.4.0]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197) ~[junit-platform-launcher-1.4.0.jar:1.4.0]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211) ~[junit-platform-launcher-1.4.0.jar:1.4.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191) ~[junit-platform-launcher-1.4.0.jar:1.4.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) ~[junit-platform-launcher-1.4.0.jar:1.4.0]
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:155) ~[junit-platform-surefire-provider-1.3.2.jar:1.3.2]
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:134) ~[junit-platform-surefire-provider-1.3.2.jar:1.3.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.1.jar:2.22.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.1.jar:2.22.1]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.1.jar:2.22.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.1.jar:2.22.1]
```

**Comment by lulf** [comment]
I think its using the wrong type. The `Schema` type is internal to the system. Instead it should use the `AddressSpaceSchema` type of which there 2 objects: `brokered` and `standard`.
