### ISSUE TITLE
Unable to open addressspace console from provisioned service via service catalog

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#2649]
**Describe the bug**
As openshift user without cluster-admin rights I create namespace and run provision addressspace via service catalog. Addressspace is successfully created and I click on dashboard link in provisioned service but I get error. Also service broker pod still generates a lot of warning.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/11318335/56091049-0bfb9880-5eaa-11e9-8249-148d3884382d.png)
![obrazek](https://user-images.githubusercontent.com/11318335/56091052-11f17980-5eaa-11e9-820e-060e42566341.png)
![obrazek](https://user-images.githubusercontent.com/11318335/56091054-15850080-5eaa-11e9-80fe-3cf788576398.png)

**Additional context**
service broker
```
2019-04-14T08:16:11.305Z INFO  [Reflector] Resync
2019-04-14T08:16:11.306Z WARN  [Reflector] Exception doing resource update
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/admin.enmasse.io/v1beta1/namespaces/myproject/consoleservices. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. consoleservices.admin.enmasse.io is forbidden: User "system:serviceaccount:myproject:service-broker" cannot list consoleservices.admin.enmasse.io in the namespace "myproject": no RBAC policy matched.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(^CBaseOperation.java:165) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:607) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:67) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.KubeCrdApi.list(KubeCrdApi.java:44) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Reflector.resync(Reflector.java:78) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Reflector.run(Reflector.java:53) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Controller.lambda$start$0(Controller.java:22) ~[service-broker.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2019-04-14T08:16:11.306Z INFO  [Reflector] Resync
2019-04-14T08:16:11.306Z WARN  [Reflector] Exception doing resource update
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/admin.enmasse.io/v1beta1/namespaces/myproject/consoleservices. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. consoleservices.admin.enmasse.io is forbidden: User "system:serviceaccount:myproject:service-broker" cannot list consoleservices.admin.enmasse.io in the namespace "myproject": no RBAC policy matched.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:165) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:607) ~[service-broker.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:67) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.KubeCrdApi.list(KubeCrdApi.java:44) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Reflector.resync(Reflector.java:78) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Reflector.run(Reflector.java:53) ~[service-broker.jar:na]
	at io.enmasse.k8s.api.cache.Controller.lambda$start$0(Controller.java:22) ~[service-broker.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by kornys** [comment]
@lulf and because service broker log is too long testAccessLogs fails.

**Comment by lulf** [comment]
Try again with fixes on master. There was a missing permission for listing console services in the service broker. (Just committed this to master, just need to regenerate templates and reinstall)

**Comment by lulf** [comment]
@kornys @k-wall I think I know the issue why the user is not permitted to read the console: the address space is created in the 'enmasse-infra' namespace and not the users namespace.
