### ISSUE TITLE
MQTT subscribe fails with MqttException during test runs - Unrecognised topic: mytopic

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2887]
I am seeing tests such as `PublishTest`, `CertProviderTestm` `InteroperabilityTest` fail with with the following client side exception during Jenkins test runs of a release-0.28 derivative.  I am seeing these errors over a number of test runs in this particular test environment. The tests seem stable elsewhere.

```
2019-06-08T12:59:49.726Z &amp#27;[1;31mERROR&amp#27;[0;39m [ITestSeparator] Caught exception
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:438)
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:469)
	at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:464)
```

Internally the MQTT Gateway is reporting the following error.

```
2019-06-08T12:58:44.198Z INFO  [AmqpBridge] SUBSCRIBE [1] from MQTT client d160ffde-9579-4cc5-bff9-8a9da2b34242
2019-06-08T12:58:44.208Z INFO  [AmqpSubscriptionServiceEndpoint] AMQP subscribe delivery Rejected{error=Error{condition=amqp:precondition-failed, description='Error: Unrecognised topic: mytopic', info=null}}
2019-06-08T12:58:44.213Z INFO  [AmqpBridge] SUBACK [1] to MQTT client d160ffde-9579-4cc5-bff9-8a9da2b34242
```

Subserv logs:

```
2019-06-08T12:55:09.263Z subserv INFO  Starting subserv
2019-06-08T12:55:09.313Z subserv INFO  Subserv listening on 5672
2019-06-08T12:55:09.330Z subserv INFO  GET /api/v1/namespaces/amq-online-infra/pods?labelSelector=role%3Dbroker%2Caddresstype%3Dtopic => 200 
2019-06-08T12:55:09.337Z subserv INFO  GET /api/v1/watch/namespaces/amq-online-infra/pods?labelSelector=role%3Dbroker%2Caddresstype%3Dtopic => 200 
2019-06-08T12:58:44.045Z subserv INFO  close($mqtt.to.d160ffde-9579-4cc5-bff9-8a9da2b34242.publish)
2019-06-08T12:58:44.045Z subserv INFO  close($mqtt.to.d160ffde-9579-4cc5-bff9-8a9da2b34242.publish) succeeded
2019-06-08T12:58:44.069Z subserv INFO  subscribe($mqtt.to.d160ffde-9579-4cc5-bff9-8a9da2b34242.publish,[object Object])
2019-06-08T12:58:44.070Z subserv INFO  subscribe($mqtt.to.d160ffde-9579-4cc5-bff9-8a9da2b34242.publish,[object Object]) failed: Error: Unrecognised topic: mytopic
```

It seems that subserv has not received notification of the new topic.  It learns of the topics by watching pod events `role=broker,addresstype=topic`.  The dump of the pod objects caught by the test confirm that the pod was Running.

```
Name:               broker-sharded-a2f6e1df-91q3o9sec5-0
Namespace:          amq-online-infra
Priority:           0
PriorityClassName:  <none>
Node:               internal-node3/10.0.19.133
Start Time:         Sat, 08 Jun 2019 08:57:15 -0400
Labels:             addresstype=topic
                    app=enmasse
                    controller-revision-hash=broker-sharded-a2f6e1df-91q3o9sec5-5746475c44
                    infraType=standard
                    infraUuid=91q3o9sec5
                    name=broker-sharded-a2f6e1df-91q3o9sec5
                    role=broker
                    statefulset.kubernetes.io/pod-name=broker-sharded-a2f6e1df-91q3o9sec5-0
Annotations:        address=mytopic
                    addressSpace=routes-space
                    cluster_id=broker-sharded-a2f6e1df-91q3o9sec5
                    openshift.io/scc=restricted
                    prometheus.io/path=/metrics
                    prometheus.io/port=8080
                    prometheus.io/scrape=true
Status:             Running
IP:                 10.130.0.114
(snip)
Events:
  Type     Reason            Age               From                     Message
  ----     ------            ----              ----                     -------
  Warning  FailedScheduling  1m (x3 over 1m)   default-scheduler        pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled         1m                default-scheduler        Successfully assigned amq-online-infra/broker-sharded-a2f6e1df-91q3o9sec5-0 to internal-node3
  Warning  FailedMount       1m (x6 over 1m)   kubelet, internal-node3  MountVolume.SetUp failed for volume "broker-internal-cert" : secrets "broker-internal-cert.91q3o9sec5" not found
  Normal   Pulling           56s               kubelet, internal-node3  pulling image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq7/amq-online-1-broker-plugin:1.1"
  Normal   Pulled            55s               kubelet, internal-node3  Successfully pulled image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq7/amq-online-1-broker-plugin:1.1"
  Normal   Created           55s               kubelet, internal-node3  Created container
  Normal   Started           55s               kubelet, internal-node3  Started container
  Normal   Pulling           52s               kubelet, internal-node3  pulling image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq-broker-7/amq-broker-73-openshift:latest"
  Normal   Pulled            51s               kubelet, internal-node3  Successfully pulled image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq-broker-7/amq-broker-73-openshift:latest"
  Normal   Created           51s               kubelet, internal-node3  Created container
  Normal   Started           51s               kubelet, internal-node3  Started container
  Normal   Pulling           51s               kubelet, internal-node3  pulling image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq7/amq-online-1-topic-forwarder:1.1"
  Normal   Pulled            50s               kubelet, internal-node3  Successfully pulled image "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/amq7/amq-online-1-topic-forwarder:1.1"
  Normal   Created           50s               kubelet, internal-node3  Created container
  Normal   Started           50s               kubelet, internal-node3  Started container
  Warning  Unhealthy         2s (x4 over 32s)  kubelet, internal-node3  Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:8161; Connection refused

```

**Comment by k-wall** [comment]
Since the pod reached the running state, why did subserv fail to receive the event.  Could it be that the watch of subserv is failing and not being automatically reinstated?

**Comment by k-wall** [comment]
After reviewing subserv, the watching handling appears sound.

I believe the actual issue is fact the topic address is considered ready with first ensuring that the topic has been registered with subserv.  I think that there needs to be a check in AddressController like the router status check that ensures that the topic is registered before allowing the topic address to become ready.  I think subserves now supports only the MQTT use-case, so this check needs to be enabled iff MQTT support is enabled for the address space AND the large topic support is required for the address.

@rgodfrey @vbusch @grs any comments welcome.
