### ISSUE TITLE
FirefoxWebConsoleTest.testCannotOpenConsolePage fails sporadically

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2944]
The test `FirefoxWebConsoleTest.testCannotOpenConsolePage` is seen to fail sporadically on test runs.  The screenshots show that the dialogue was not popped up refusing the user access, but the agent logs show that the user's lack of permissions was detected properly (see log exert below.   It suggests to me a defect in the front end.

```
2019-06-26T11:06:13.961Z &amp#27;[1;31mERROR&amp#27;[0;39m [ITestSeparator] Caught exception
org.opentest4j.AssertionFailedError: Expected java.lang.IllegalAccessException to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2952)
	at io.enmasse.systemtest.standard.web.FirefoxWebConsoleTest.testCannotOpenConsolePage(FirefoxWebConsoleTest.java:221)

```

```
2019-06-26T11:04:54.184Z agent INFO  GET /apis/user.openshift.io/v1/users/~ => 200
2019-06-26T11:04:54.184Z agent INFO  User identified as : noexistuser
2019-06-26T11:04:54.577Z agent INFO  POST /apis/authorization.k8s.io/v1/selfsubjectaccessreviews => 201
2019-06-26T11:04:54.577Z agent WARN  User does not have list address permission, not granting console access. ["no RBAC policy matched"]
```

**Comment by k-wall** [comment]
Fixed by #3048
