### ISSUE TITLE
Address space hangs in Configuring state - DNS-1123 subdomain must consist of lower case alphanumeric characters

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2969]
Occasionally when creating a new standard address space, the address space fails to get beyond the Configuring phase.  The following error is reported in the address-space-controller.  The system does not recover.

```
2019-07-05T15:05:04.228Z WARN  [ControllerChain] Error syncing address space persist-plan-space
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/apis/apps/v1/namespaces/enmasse-infra/deployments. Message: Deployment.apps "admin.zhtmsfif4w" is invalid: [spec.template.spec.volumes[1].secret.secretName: Required value, spec.template.spec.containers[1].env[17].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[1].env[18].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[1].env[19].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.volumes[1].secret.secretName, message=Required value, reason=FieldValueRequired, additionalProperties={}), StatusCause(field=spec.template.spec.containers[1].env[17].valueFrom.secretKeyRef.name, message=Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.template.spec.containers[1].env[18].valueFrom.secretKeyRef.name, message=Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.template.spec.containers[1].env[19].valueFrom.secretKeyRef.name, message=Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=admin.zhtmsfif4w, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "admin.zhtmsfif4w" is invalid: [spec.template.spec.volumes[1].secret.secretName: Required value, spec.template.spec.containers[1].env[17].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[1].env[18].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[1].env[19].valueFrom.secretKeyRef.name: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:417)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:801)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:381)
        at io.fabric8.kubernetes.client.handlers.DeploymentHandler.create(DeploymentHandler.java:46)
        at io.fabric8.kubernetes.client.handlers.DeploymentHandler.create(DeploymentHandler.java:38)
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:139)
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:82)
        at io.fabric8.kubernetes.client.dsl.internal.KubernetesListOperationsImpl.create(KubernetesListOperationsImpl.java:47)
        at io.enmasse.controller.common.KubernetesHelper.create(KubernetesHelper.java:45)
        at io.enmasse.controller.CreateController.reconcile(CreateController.java:146)
        at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:100)
        at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:49)
        at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:39)
```

**Comment by k-wall** [comment]
I've seen this error twice now, once on my local development environment and once for a Jenkins test run.

**Comment by k-wall** [comment]
The error message is two-fold: 

* spec.template.spec.volumes[1].secret.secretName: Required value
* spec.template.spec.containers[1].env[17].valueFrom.secretKeyRef.name: Invalid value: ""

both of these refer to the variable `CONSOLE_SSO_COOKIE_SECRET_SECRET_NAME `which is supposed to refer to a secret name.

**Comment by k-wall** [comment]
I note that `spec.template.spec.volumes[1].secret.secretName` is actually redundant.

**Comment by k-wall** [comment]
The console server redesign has removed this issue.
