### ISSUE TITLE
Addresses (broker pods) are not fully deleted 

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#3456]
**Describe the bug**
During running shared test suite we can see that broker pods in infra namespaces are not deleted when addresses are removed. 

It caused fails in our systemtests suite because pods consumes all resources on nodes so another tests cannot create another address (pods)

**Additional context**
oc get events
```
2019-11-12T11:18:06Z   2019-11-12T10:03:20Z   331       standard-controller.1070108445                       Address       <none>    Warning   BrokerDeleteFailed   standard-controller      Error deleting broker cluster broker-b41e7da-pj2k: Failure executing: PATCH at: https://172.30.0.1/apis/apps/v1/namespaces/enmasse-infra/statefulsets/broker-b41e7da-pj2k. Message: StatefulSet.apps "broker-b41e7da-pj2k" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden., reason=FieldValueForbidden, additionalProperties={})], group=apps, kind=StatefulSet, name=broker-b41e7da-pj2k, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=StatefulSet.apps "broker-b41e7da-pj2k" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden., metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

**Comment by kornys** [comment]
@lulf also admin pods are not deleted

**Comment by k-wall** [comment]
Is there a particular test that is known to show this issue?

**Comment by kornys** [comment]
@k-wall nope, issue appears after many test in shared space. You can check logs in master jenkins shared job

**Comment by kornys** [comment]
@k-wall check this test io.enmasse.systemtest.shared.standard.TopicTest.testShardedTopic

**Comment by lulf** [comment]
@kornys @k-wall  I'll have a look, its probably related to CRD refactor

**Comment by lulf** [comment]
@k-wall I'm starting to think it might be related to the new kubernetes-client version. The following is shown in the standard-controller logs:

```
2019-11-12T11:12:15.097Z WARN  [AddressController] Error deleting cluster broker-b41e7da-9zv3
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.30.0.1/apis/apps/v1/namespaces/enmasse-infra/statefulsets/bro
ker-b41e7da-9zv3. Message: StatefulSet.apps "broker-b41e7da-9zv3" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', '
template', and 'updateStrategy' are forbidden.. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message
=Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden., reason=FieldValueForbidden, additio
nalProperties={})], group=apps, kind=StatefulSet, name=broker-b41e7da-9zv3, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=S
tatefulSet.apps "broker-b41e7da-9zv3" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrate
gy' are forbidden., metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:300)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:829)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:152)
        at io.fabric8.kubernetes.api.model.apps.DoneableStatefulSet.done(DoneableStatefulSet.java:27)
        at io.fabric8.kubernetes.api.model.apps.DoneableStatefulSet.done(DoneableStatefulSet.java:6)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:158)
        at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.patch(RollableScalableResourceOperation.java:167)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$edit$0(HasMetadataOperation.java:53)
        at io.fabric8.kubernetes.api.model.apps.DoneableStatefulSet.done(DoneableStatefulSet.java:27)
        at io.fabric8.kubernetes.client.dsl.internal.StatefulSetOperationsImpl.withReplicas(StatefulSetOperationsImpl.java:62)
        at io.fabric8.kubernetes.client.dsl.internal.StatefulSetOperationsImpl.withReplicas(StatefulSetOperationsImpl.java:35)
        at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.scale(RollableScalableResourceOperation.java:74)
        at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.scale(RollableScalableResourceOperation.java:42)
        at io.fabric8.kubernetes.client.dsl.internal.ScalableReaper.reap(ScalableReaper.java:30)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:648)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:69)
        at io.fabric8.kubernetes.client.handlers.StatefulSetHandler.delete(StatefulSetHandler.java:73)
        at io.fabric8.kubernetes.client.handlers.StatefulSetHandler.delete(StatefulSetHandler.java:39)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.delete(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:162)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.delete(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:59)
        at io.enmasse.controller.standard.KubernetesHelper.lambda$delete$2(KubernetesHelper.java:169)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at io.enmasse.controller.standard.KubernetesHelper.delete(KubernetesHelper.java:169)


```

**Comment by lulf** [comment]
@obabec I think is a different issue though, this issue is about brokers being kept around when addresses are deleted (Correct me if I'm wrong @kornys ). The work in #3452 might fix what you are seeing, have you tested with that?

**Comment by kornys** [comment]
@lulf you are probably right, issue which ondrej see is little bit different. From log what ondrej reported I see that cr of addressspaces are deleted but stateful sets and deployments of addressspace and address not.

**Comment by k-wall** [comment]
@kornys I think this issue is now closable.
