### ISSUE TITLE
Agent seen to restart following "failed to retrieve addresses" and "transfer after detach"

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4081]
The following error was encountered testing a near release-0.31 version of Agent by @vbusch.

```
2020-03-09T21:34:43.142Z agent INFO  checking configuration of qdrouterd-64e7b8b-2
2020-03-09T21:34:43.143Z agent INFO  [mgmt:qdrouterd-64e7b8b-0] router ready
2020-03-09T21:34:43.220Z agent INFO  checking configuration of qdrouterd-64e7b8b-0
2020-03-09T21:34:43.222Z agent INFO  [broker-64e7b8b-7maj-0] broker controller ready
2020-03-09T21:34:43.222Z agent INFO  broker broker-64e7b8b-7maj-0 connected
2020-03-09T21:34:44.542Z agent INFO  [broker-64e7b8b-djxq-0] ready to send requests, reply to address: activemq.management.tmpreply.9b078279-df9b-b249-ac9a-05afe52af295
2020-03-09T21:34:44.545Z agent INFO  [broker-64e7b8b-41xv-0] ready to send requests, reply to address: activemq.management.tmpreply.5ca202d7-9b24-b54a-b06f-7412acc4b9ce
2020-03-09T21:34:54.533Z agent INFO  [broker-64e7b8b-7maj-0] ready to send requests, reply to address: activemq.management.tmpreply.6741f429-4f79-0a45-b368-ef90e0fd6aed
2020-03-09T21:34:54.772Z agent INFO  [broker-64e7b8b-41xv-0] disconnected
2020-03-09T21:34:54.772Z agent INFO  broker disconnected: broker-64e7b8b-41xv-0
2020-03-09T21:34:54.775Z agent ERROR [broker-64e7b8b-41xv-0] failed to retrieve connectors: undefined
2020-03-09T21:34:54.775Z agent ERROR [broker-64e7b8b-41xv-0] failed to retrieve addresses: undefined
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: transfer after detach
    at Incoming.on_transfer (/opt/app-root/src/node_modules/rhea/lib/session.js:364:15)
    at Session.on_transfer (/opt/app-root/src/node_modules/rhea/lib/session.js:749:19)
    at Connection.(anonymous function) [as on_transfer] (/opt/app-root/src/node_modules/rhea/lib/connection.js:783:30)
    at c.dispatch (/opt/app-root/src/node_modules/rhea/lib/types.js:910:33)
    at Transport.read (/opt/app-root/src/node_modules/rhea/lib/transport.js:109:36)
    at SaslServer.read (/opt/app-root/src/node_modules/rhea/lib/sasl.js:232:26)
    at SelectiveServer.read (/opt/app-root/src/node_modules/rhea/lib/sasl.js:367:26)
    at Connection.input (/opt/app-root/src/node_modules/rhea/lib/connection.js:517:35)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
Emitted 'error' event at:
    at Container.dispatch (/opt/app-root/src/node_modules/rhea/lib/container.js:41:33)
    at Connection.dispatch (/opt/app-root/src/node_modules/rhea/lib/connection.js:244:40)
    at Connection.input (/opt/app-root/src/node_modules/rhea/lib/connection.js:535:18)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by k-wall** [comment]
I think stack suggests that the broker is sending a transfer (a management response) over a link that has already been detached.  Rhea is detecting the condition and generating an `error` event.  This error event is not being handled, so it is bubbling all the way to the top.

**Comment by grs** [comment]
@k-wall yes, that is certainly what the rhea client is complaining about. Would need to verify via a protocol trace to be sure about who is to blame.
