### ISSUE TITLE
Running SmokeTests of Minikube 1.8.1 on Fedora 30 fails with  java.lang.RuntimeException: gio

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4183]
**Describe the bug**

```
$ minikube version
minikube version: v1.8.1
commit: cbda04cf6bbe65e987ae52bb393c10099ab62014
```

Running the SmokeTests (for release-0.30) on Fedora 30 fails like so:

```
[ERROR] testAddressTypes  Time elapsed: 59.678 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: gio: file:///home/keith/go/src/github.com/enmasseproject/enmasse/systemtests/192.168.39.148: Error when getting information for file “/home/keith/go/src/github.com/enmasseproject/enmasse/systemtests/192.168.39.148”: No such file or directory* X open url failed: 192.168.39.148: exit status 4* * minikube is exiting due to an error. If the above message is not useful, open an issue:  - https://github.com/kubernetes/minikube/issues/new/choose
	at io.enmasse.systemtest.platform.Minikube.runCommand(Minikube.java:55)
	at io.enmasse.systemtest.platform.Minikube.getIp(Minikube.java:60)
	at io.enmasse.systemtest.platform.Minikube.getExternalEndpoint(Minikube.java:95)
	at io.enmasse.systemtest.platform.Minikube.getExternalEndpoint(Minikube.java:86)
	at io.enmasse.systemtest.amqp.AmqpClientFactory.createClient(AmqpClientFactory.java:94)
	at io.enmasse.systemtest.amqp.AmqpClientFactory.createQueueClient(AmqpClientFactory.java:48)
```

Could the semantics of the `service` cmd line argument have changed?  minikube service default behaviour seems to try to pop a browser.

Reproducing the issue on the command line outside of the tests, I see:

```
 $minikube service -n enmasse-infra --format {{.IP}} messaging-aov170fshz-external
|---------------|-------------------------------|-------------|----------------|
|   NAMESPACE   |             NAME              | TARGET PORT |      URL       |
|---------------|-------------------------------|-------------|----------------|
| enmasse-infra | messaging-aov170fshz-external | amqps       | 192.168.39.148 |
|---------------|-------------------------------|-------------|----------------|
* Opening service enmasse-infra/messaging-aov170fshz-external in default browser...
gio: file:///tmp/enmasse/192.168.39.148: Error when getting information for file “/tmp/enmasse/192.168.39.148”: No such file or directory
*
X open url failed: 192.168.39.148: exit status 4
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**To Reproduce**
1. make SYSTEMTEST_ARGS=SmokeTest systemtests

**Expected behavior**
SmokeTests should pass.

**Additional context**

**Comment by k-wall** [comment]
I notice the Minikube.getIp looks unchanged, so I expect I would see the same issue there.
Changing the command line arguments to include `--url=true` prevents the issue for me.

**Comment by k-wall** [comment]
Possible relates to the following defect:

https://github.com/kubernetes/minikube/issues/5789
