### ISSUE TITLE
'Message not accepted' after sending message to address which is created/removed in loop

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#429]
### description: 
- when 2 addresses are deployed into default address space (1 message is send to first of them) and one by one are removed, then time to time is connection rejected with following message: _**Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent**_

### prerequisites:
- enmasse running in multitenant mode: `sh ./templates/install/deploy-openshift.sh -a "none standard" -o "multitenant"`
### steps to reproduce:
1. execute already existing test: (is required to uncomment `runQueueTest(client, address, 1);` line in this test)
`make MULTITENANT=true SYSTEMTEST_ARGS='standard.QueueTest#testCreateDeleteQueue' systemtests`
https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L129
2. output from test:
```
2108148 [main] INFO test - Test is running in multitenant mode
2108148 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/ with host: restapi-jenkins-enmasse-1308.172.16.84.22.xip.io with Port: 80
2108154 [vert.x-eventloop-thread-0] INFO test - Following list of address spaces received{"apiVersion":"enmasse.io/v1","kind":"AddressSpaceList","items":[{"metadata":{"name":"testspace","namespace":"testspace"},"spec":{"type":"standard","plan":"unlimited","endpoints":[{"name":"console","service":"console","host":"console-testspace.172.16.84.22.xip.io"},{"name":"messaging","service":"messaging","host":"messaging-testspace.172.16.84.22.xip.io","certProvider":{"name":"secret","secretName":"external-certs-messaging"}},{"name":"mqtt","service":"mqtt","host":"mqtt-testspace.172.16.84.22.xip.io","certProvider":{"name":"secret","secretName":"external-certs-mqtt"}}],"authenticationService":{"type":"standard","details":{}}},"status":{"isReady":true}}]}
2108155 [main] INFO test - Address space '{name=testspace,namespace=testspace}' already exists.
2108155 [main] INFO test - Waiting for 2 minutes before starting tests
2108159 [main] INFO test - Testing endpoint : keycloak-jenkins-enmasse-1308.172.16.84.22.xip.io:80
2108160 [main] INFO test - Logging into keycloak with admin/HLBl9IsqODXuh42BSodR1YHNOMQFnLCb
2108170 [main] INFO test - Waiting for realm testspace to exist
2108431 [main] INFO test - User systemtest already created, skipping
2108437 [main] INFO test - External endpoint: messaging-testspace.172.16.84.22.xip.io:443, internal: messaging-testspace.172.16.84.22.xip.io:443
2108437 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
2108437 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"queue-create-delete-0","addressSpace":"testspace"},"spec":{"address":"queue-create-delete-0","type":"queue","plan":"pooled-inmemory"}},{"metadata":{"name":"ext-queue","addressSpace":"testspace"},"spec":{"address":"ext-queue","type":"queue","plan":"pooled-inmemory"}}]}
2108469 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/testspace with host: restapi-jenkins-enmasse-1308.172.16.84.22.xip.io with Port: 80
2108505 [pool-22-thread-1] INFO test - Waiting for pod pooled-inmemory-3338272626-w50sd to start
2110512 [pool-22-thread-1] INFO test - Collecting logs for pod pooled-inmemory-3338272626-w50sd in namespace testspace
2113483 [main] INFO test - Waiting for 6 pods
2113488 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2113495 [main] INFO test - Checking queue-create-delete-0 for ready state
2118495 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2118503 [main] INFO test - Checking queue-create-delete-0 for ready state
2123503 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2123511 [main] INFO test - Checking queue-create-delete-0 for ready state
2123590 [vert.x-eventloop-thread-0] INFO test - Sender link 'queue-create-delete-0' opened, sending messages
2123666 [vert.x-eventloop-thread-0] INFO test - Receiver link 'queue-create-delete-0' opened, granting credits
2123685 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2123710 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2123718 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
2123719 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"queue-create-delete-1","addressSpace":"testspace"},"spec":{"address":"queue-create-delete-1","type":"queue","plan":"pooled-inmemory"}},{"metadata":{"name":"ext-queue","addressSpace":"testspace"},"spec":{"address":"ext-queue","type":"queue","plan":"pooled-inmemory"}}]}
2123747 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/testspace with host: restapi-jenkins-enmasse-1308.172.16.84.22.xip.io with Port: 80
2123761 [main] INFO test - Waiting for 6 pods
2123766 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2123785 [main] INFO test - Checking queue-create-delete-1 for ready state
2123876 [pool-22-thread-1] INFO test - Waiting for pod pooled-inmemory-3338272626-pnbtq to start
2125893 [pool-22-thread-1] INFO test - Collecting logs for pod pooled-inmemory-3338272626-pnbtq in namespace testspace
2128785 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2128794 [main] INFO test - Checking queue-create-delete-1 for ready state
2133794 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2133802 [main] INFO test - Checking queue-create-delete-1 for ready state
2138802 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2138811 [main] INFO test - Checking queue-create-delete-1 for ready state
2138885 [vert.x-eventloop-thread-0] INFO test - Sender link 'queue-create-delete-1' opened, sending messages
2138889 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
2138889 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[]}
2138914 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/testspace with host: restapi-jenkins-enmasse-1308.172.16.84.22.xip.io with Port: 80
2138922 [main] INFO test - Waiting for 5 pods
2171058 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
2171067 [main] INFO test - Checking {} for ready state
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 226.719 s <<< FAILURE! - in io.enmasse.systemtest.standard.QueueTest
[ERROR] testCreateDeleteQueue(io.enmasse.systemtest.standard.QueueTest)  Time elapsed: 62.932 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent
	at io.enmasse.systemtest.standard.QueueTest.runQueueTest(QueueTest.java:213)
	at io.enmasse.systemtest.standard.QueueTest.testCreateDeleteQueue(QueueTest.java:129)
Caused by: java.lang.IllegalStateException: Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent

```

### potential problem
is that even though the address is deleted from the address controller, it might take some time for the address to be gone from the system in general

**Comment by grs** [comment]
Does the test wait until the message is accepted before deleting the address? (If not, it should).

**Comment by tkratky** [comment]
yes here: https://github.com/EnMasseProject/enmasse/blob/master/systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java#L213
address shouldn't be removed before all messages are sent/received

**Comment by tkratky** [comment]
added logging when address is removed to be sure: https://github.com/EnMasseProject/enmasse/pull/430

**Comment by grs** [comment]
For a message to be rejected, it must be unsettled. If we get a protocol trace we can identify which delivery is being rejected.

**Comment by tkratky** [comment]
I'll try to reproduce and put here more info

**Comment by tkratky** [comment]
I'm not able to reproduce with PN_TRACE_FRM=1 because test is failing on unavailable application again:

```
281028 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces/testspace with host: restapi-myproject.127.0.0.1.nip.io with Port: 80
281996 [main] INFO test - Waiting for 6 pods
282010 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
282157 [main] INFO test - Checking queue-create-delete-6 for ready state
287172 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
287894 [main] INFO test - Checking queue-create-delete-6 for ready state
292895 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
293178 [main] INFO test - Checking queue-create-delete-6 for ready state
298178 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
301166 [vert.x-eventloop-thread-0] WARN test - Error when getting addresses
io.vertx.core.VertxException: Connection was closed
	at io.vertx.core.http.impl.ClientConnection.handleClosed(ClientConnection.java:406)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:134)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
301195 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
301195 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[]}
301273 [vert.x-eventloop-thread-0] WARN test - Error when deploying addresses
io.vertx.core.json.DecodeException: Failed to decode: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html>

```

maybe fixing issue #433 will fix this issue as well

**Comment by tkratky** [comment]
@grs will following trace useful for identifying which delivery was rejected?

```
Error Message

java.lang.IllegalStateException: Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent

Stacktrace

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent
	at io.enmasse.systemtest.standard.QueueTest.runQueueTest(QueueTest.java:213)
	at io.enmasse.systemtest.standard.QueueTest.testCreateDeleteQueue(QueueTest.java:129)
Caused by: java.lang.IllegalStateException: Message not accepted (remote state: Rejected{error=Error{condition=failed, description='null', info=null}}) after 0 messages sent

Standard Output

[1275444928:0] -> Open{ containerId='enmasse-systemtest-client', hostname='messaging-testspace.127.0.0.1.nip.io', maxFrameSize=32768, channelMax=65535, idleTimeOut=null, outgoingLocales=null, incomingLocales=null, offeredCapabilities=null, desiredCapabilities=null, properties={product=vertx-proton, version=3.5.0}}
[1275444928:0] <- Open{ containerId='Router.qdrouterd-1471036403-ht2k3', hostname='null', maxFrameSize=16384, channelMax=32767, idleTimeOut=8000, outgoingLocales=null, incomingLocales=null, offeredCapabilities=[ANONYMOUS-RELAY], desiredCapabilities=null, properties={product=qpid-dispatch-router, version=1.0.0}}
[1275444928:0] -> Begin{remoteChannel=null, nextOutgoingId=1, incomingWindow=65535, outgoingWindow=2147483647, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1275444928:0] -> Attach{name='auto-0', handle=0, role=SENDER, sndSettleMode=UNSETTLED, rcvSettleMode=FIRST, source=Source{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=[amqp:accepted:list, amqp:rejected:list, amqp:released:list, amqp:modified:list], capabilities=null}, target=Target{address='queue-create-delete-0', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=null, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1275444928:0] <- Begin{remoteChannel=0, nextOutgoingId=0, incomingWindow=2147483647, outgoingWindow=2147483647, handleMax=4294967295, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1275444928:0] <- Attach{name='auto-0', handle=0, role=RECEIVER, sndSettleMode=MIXED, rcvSettleMode=FIRST, source=Source{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=[amqp:accepted:list, amqp:rejected:list, amqp:released:list, amqp:modified:list], capabilities=null}, target=Target{address='queue-create-delete-0', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=0, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1275444928:0] <- Flow{nextIncomingId=1, incomingWindow=2147483647, nextOutgoingId=0, outgoingWindow=2147483647, handle=0, deliveryCount=0, linkCredit=250, available=null, drain=false, echo=false, properties=null}
[1275444928:0] -> Transfer{handle=0, deliveryId=0, deliveryTag=1, messageFormat=0, settled=null, more=false, rcvSettleMode=null, state=null, resume=false, aborted=false, batchable=false} (48) "\x00Ss\xc0\x1a\x03@@\xa1\x15queue-create-delete-0\x00Sw\xa1\x0ctestmessage0"
[1275444928:0] <- Flow{nextIncomingId=2, incomingWindow=2147483647, nextOutgoingId=0, outgoingWindow=2147483647, handle=0, deliveryCount=1, linkCredit=250, available=null, drain=false, echo=false, properties=null}
[1275444928:0] <- Disposition{role=RECEIVER, first=0, last=0, settled=true, state=Accepted{}, batchable=false}
[1275444928:0] -> Close{error=null}
[1275444928:0] <- Close{error=null}
[1953084111:0] -> Open{ containerId='enmasse-systemtest-client', hostname='messaging-testspace.127.0.0.1.nip.io', maxFrameSize=32768, channelMax=65535, idleTimeOut=null, outgoingLocales=null, incomingLocales=null, offeredCapabilities=null, desiredCapabilities=null, properties={product=vertx-proton, version=3.5.0}}
[1953084111:0] <- Open{ containerId='Router.qdrouterd-1471036403-ht2k3', hostname='null', maxFrameSize=16384, channelMax=32767, idleTimeOut=8000, outgoingLocales=null, incomingLocales=null, offeredCapabilities=[ANONYMOUS-RELAY], desiredCapabilities=null, properties={product=qpid-dispatch-router, version=1.0.0}}
[1953084111:0] -> Begin{remoteChannel=null, nextOutgoingId=1, incomingWindow=65535, outgoingWindow=2147483647, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1953084111:0] -> Attach{name='queue-create-delete-0', handle=0, role=RECEIVER, sndSettleMode=UNSETTLED, rcvSettleMode=FIRST, source=Source{address='queue-create-delete-0', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}, target=Target{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=null, maxMessageSize=null, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1953084111:0] <- Begin{remoteChannel=0, nextOutgoingId=0, incomingWindow=2147483647, outgoingWindow=2147483647, handleMax=4294967295, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1953084111:0] <- Attach{name='queue-create-delete-0', handle=0, role=SENDER, sndSettleMode=MIXED, rcvSettleMode=FIRST, source=Source{address='queue-create-delete-0', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}, target=Target{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=0, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[1953084111:0] -> Flow{nextIncomingId=0, incomingWindow=65535, nextOutgoingId=1, outgoingWindow=2147483647, handle=0, deliveryCount=0, linkCredit=1, available=null, drain=false, echo=false, properties=null}
[1953084111:0] <- Transfer{handle=0, deliveryId=0, deliveryTag=\x8b#\x00\x00\x00\x00\x00\x00, messageFormat=0, settled=false, more=false, rcvSettleMode=null, state=null, resume=false, aborted=false, batchable=false} (48) "\x00Ss\xc0\x1a\x03@@\xa1\x15queue-create-delete-0\x00Sw\xa1\x0ctestmessage0"
[1953084111:0] -> Disposition{role=RECEIVER, first=0, last=0, settled=true, state=Accepted{}, batchable=false}
[1953084111:0] -> Close{error=null}
[1953084111:0] <- Close{error=null}
[2115870334:0] -> Open{ containerId='enmasse-systemtest-client', hostname='messaging-testspace.127.0.0.1.nip.io', maxFrameSize=32768, channelMax=65535, idleTimeOut=null, outgoingLocales=null, incomingLocales=null, offeredCapabilities=null, desiredCapabilities=null, properties={product=vertx-proton, version=3.5.0}}
[2115870334:0] <- Open{ containerId='Router.qdrouterd-1471036403-ht2k3', hostname='null', maxFrameSize=16384, channelMax=32767, idleTimeOut=8000, outgoingLocales=null, incomingLocales=null, offeredCapabilities=[ANONYMOUS-RELAY], desiredCapabilities=null, properties={product=qpid-dispatch-router, version=1.0.0}}
[2115870334:0] -> Begin{remoteChannel=null, nextOutgoingId=1, incomingWindow=65535, outgoingWindow=2147483647, handleMax=65535, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[2115870334:0] -> Attach{name='auto-0', handle=0, role=SENDER, sndSettleMode=UNSETTLED, rcvSettleMode=FIRST, source=Source{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=[amqp:accepted:list, amqp:rejected:list, amqp:released:list, amqp:modified:list], capabilities=null}, target=Target{address='queue-create-delete-1', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=null, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[2115870334:0] <- Begin{remoteChannel=0, nextOutgoingId=0, incomingWindow=2147483647, outgoingWindow=2147483647, handleMax=4294967295, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[2115870334:0] <- Attach{name='auto-0', handle=0, role=RECEIVER, sndSettleMode=MIXED, rcvSettleMode=FIRST, source=Source{address='null', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=[amqp:accepted:list, amqp:rejected:list, amqp:released:list, amqp:modified:list], capabilities=null}, target=Target{address='queue-create-delete-1', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}, unsettled=null, incompleteUnsettled=false, initialDeliveryCount=0, maxMessageSize=0, offeredCapabilities=null, desiredCapabilities=null, properties=null}
[2115870334:0] <- Flow{nextIncomingId=1, incomingWindow=2147483647, nextOutgoingId=0, outgoingWindow=2147483647, handle=0, deliveryCount=0, linkCredit=250, available=null, drain=false, echo=false, properties=null}
[2115870334:0] -> Transfer{handle=0, deliveryId=0, deliveryTag=1, messageFormat=0, settled=null, more=false, rcvSettleMode=null, state=null, resume=false, aborted=false, batchable=false} (48) "\x00Ss\xc0\x1a\x03@@\xa1\x15queue-create-delete-1\x00Sw\xa1\x0ctestmessage0"
[2115870334:0] <- Flow{nextIncomingId=2, incomingWindow=2147483647, nextOutgoingId=0, outgoingWindow=2147483647, handle=0, deliveryCount=1, linkCredit=250, available=null, drain=false, echo=false, properties=null}
[2115870334:0] <- Disposition{role=RECEIVER, first=0, last=0, settled=true, state=Rejected{error=Error{condition=failed, description='null', info=null}}, batchable=false}
[2115870334:0] -> Close{error=null}
[2115870334:0] <- Close{error=null}

Standard Error

3542750 [main] INFO test - Test is running in multitenant mode
3542750 [main] INFO test - Following HTTP request will be used for getting address space:/v1/addressspaces with host: restapi-jenkins-enmasse-branches-issue-429-create-delete-3.127.0.0.1.nip.io with Port: 80
3542758 [main] INFO test - Following list of address spaces received[{"metadata":{"name":"testspace","namespace":"testspace"},"spec":{"type":"standard","plan":"unlimited","endpoints":[{"name":"console","service":"console","host":"console-testspace.127.0.0.1.nip.io"},{"name":"messaging","service":"messaging","host":"messaging-testspace.127.0.0.1.nip.io","certProvider":{"name":"secret","secretName":"external-certs-messaging"}},{"name":"mqtt","service":"mqtt","host":"mqtt-testspace.127.0.0.1.nip.io","certProvider":{"name":"secret","secretName":"external-certs-mqtt"}}],"authenticationService":{"type":"standard","details":{}}},"status":{"isReady":true}}]
3542758 [main] INFO test - Address space '{name=testspace,namespace=testspace,type=standard}' already exists.
3542758 [main] INFO test - Waiting for 2 minutes before starting tests
3542762 [main] INFO test - Testing endpoint : keycloak-jenkins-enmasse-branches-issue-429-create-delete-3.127.0.0.1.nip.io:80
3542763 [main] INFO test - Logging into keycloak with admin/gg6VFJ3DU0x96UrFoIxbxyhDj7CXFbKW
3542769 [main] INFO test - Waiting for realm testspace to exist
3543066 [main] INFO test - User systemtest already created, skipping
3543079 [main] INFO test - External endpoint: messaging-testspace.127.0.0.1.nip.io:443, internal: messaging-testspace.127.0.0.1.nip.io:443
3543080 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
3543080 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"queue-create-delete-0","addressSpace":"testspace"},"spec":{"address":"queue-create-delete-0","type":"queue","plan":"pooled-inmemory"}},{"metadata":{"name":"ext-queue","addressSpace":"testspace"},"spec":{"address":"ext-queue","type":"queue","plan":"pooled-inmemory"}}]}
3543157 [pool-96-thread-1] INFO test - Waiting for pod pooled-inmemory-830409406-4dbwh to start
3545167 [pool-96-thread-1] INFO test - Collecting logs for pod pooled-inmemory-830409406-4dbwh in namespace testspace
3548131 [main] INFO test - Waiting for 6 pods
3548137 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3548150 [main] INFO test - Checking queue-create-delete-0 for ready state
3553150 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3553161 [main] INFO test - Checking queue-create-delete-0 for ready state
3558161 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3558173 [main] INFO test - Checking queue-create-delete-0 for ready state
3558251 [vert.x-eventloop-thread-0] INFO test - Sender link 'queue-create-delete-0' opened, sending messages
3558329 [vert.x-eventloop-thread-0] INFO test - Receiver link 'queue-create-delete-0' opened, granting credits
3558349 [vert.x-eventloop-thread-0] INFO test - Address queue-create-delete-0 successfully removed
3558349 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3558385 [vert.x-eventloop-thread-0] INFO test - Address ext-queue successfully removed
3558385 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3558402 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
3558402 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"queue-create-delete-1","addressSpace":"testspace"},"spec":{"address":"queue-create-delete-1","type":"queue","plan":"pooled-inmemory"}},{"metadata":{"name":"ext-queue","addressSpace":"testspace"},"spec":{"address":"ext-queue","type":"queue","plan":"pooled-inmemory"}}]}
3558460 [main] INFO test - Waiting for 6 pods
3558468 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3558488 [main] INFO test - Checking queue-create-delete-1 for ready state
3558557 [pool-96-thread-1] INFO test - Waiting for pod pooled-inmemory-830409406-w6qlw to start
3560565 [pool-96-thread-1] INFO test - Collecting logs for pod pooled-inmemory-830409406-w6qlw in namespace testspace
3563488 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3563499 [main] INFO test - Checking queue-create-delete-1 for ready state
3568500 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3568510 [main] INFO test - Checking queue-create-delete-1 for ready state
3573511 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3573522 [main] INFO test - Checking queue-create-delete-1 for ready state
3573600 [vert.x-eventloop-thread-0] INFO test - Sender link 'queue-create-delete-1' opened, sending messages
3573605 [main] INFO test - Following HTTP request will be used for deploy: /v1/addresses/testspace/
3573605 [main] INFO test - Following payload will be used in request: {"apiVersion":"v1","kind":"AddressList","items":[]}
3573644 [main] INFO test - Waiting for 5 pods
3605782 [main] INFO test - Following HTTP request will be used for getting address: /v1/addresses/testspace
3605793 [main] INFO test - Checking {} for ready state

```

**Comment by lulf** [comment]
@grs @tkratky I think perhaps the reason for rejection is that even though the address status is ready, the pooled broker might not have the address created yet. When we have a working status check I think you can reenable it.

**Comment by tkratky** [comment]
@lulf works fine with enabled simple send/receive, I presume that this issue could be closed, do you agree?

**Comment by kornys** [comment]
@tkratky Yes It should be, I guess. As Ulf said after better status checking, which is now completed.

**Comment by lulf** [comment]
@tkratky There is one final thing on deletion that needs to be fixed as well. Basically we need to make the rest api put the address into Terminating rather than deleting it, and then the controller will delete it once all status checks fail. Then the systemtest framework will know that is is safe to proceed when the address is gone (mainly this is for tests recreating addresses with the same name).
