### ISSUE TITLE
Cannot replace addressspace plan with different infra config

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#4364]
**Describe a bug**
When I update addressspace plan with different infra, it is not updated and standard_controller writes exceptions in logs

**To Reproduce**
run test -> **InfraTestStandard#testIncrementInfra**

**Additional context**
```
659   │ [305.570s][info][gc] GC(45) Pause Young (Allocation Failure) 52M->32M(85M) 2.764ms
 660   │ [305.724s][info][gc] GC(46) Pause Young (Allocation Failure) 53M->32M(85M) 3.079ms
 661   │ [305.812s][info][gc] GC(47) Pause Young (Allocation Failure) 53M->32M(85M) 1.638ms
 662   │ 2020-04-22T10:11:29.528Z INFO  [AddressController] Total: 1, Active: 1, Configuring: 0, Pending: 0, Terminating: 0, Failed: 0
 663   │ 2020-04-22T10:11:29.528Z INFO  [AddressController] Usage: {router={all={used=1.0, needed=1}}, broker={broker-32ce845-qa45={used=1.0, needed=1}}}
 664   │ 2020-04-22T10:11:29.528Z INFO  [AddressController] Needed: {router={all={used=1.0, needed=1}}, broker={broker-32ce845-qa45={used=1.0, needed=1}}}
 665   │ [313.558s][info][gc] GC(48) Pause Young (Allocation Failure) 53M->33M(85M) 1.851ms
 666   │ 2020-04-22T10:11:30.073Z INFO  [Artemis] Retrieving address names for broker broker-32ce845-qa45-0
 667   │ [314.039s][info][gc] GC(49) Pause Young (Allocation Failure) 54M->33M(85M) 2.043ms
 668   │ 2020-04-22T10:11:30.505Z INFO  [Artemis] Retrieving queue names for broker broker-32ce845-qa45-0
 669   │ 2020-04-22T10:11:30.518Z INFO  [AddressController] Upgrading broker broker-32ce845-qa45
 670   │ 2020-04-22T10:11:30.553Z WARN  [ResourceChecker] Exception in checker task
 671   │ io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1/apis/apps/v1/namespaces/enmasse-infra/statefulsets/broker-32ce845-qa45
       │ . Message: StatefulSet.apps "broker-32ce845-qa45" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy
       │ ' are forbidden. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: updates to statefulset spec for f
       │ ields other than 'replicas', 'template', and 'updateStrategy' are forbidden, reason=FieldValueForbidden, additionalProperties={})], group=apps, kind=StatefulSet, name=broke
       │ r-32ce845-qa45, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=StatefulSet.apps "broker-32ce845-qa45" is invalid: spec: Forbidden: updates
       │  to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVe
       │ rsion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
 672   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)
 673   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449)
 674   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413)
 675   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)
 676   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:279)
 677   │     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:259)
 678   │     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:824)
 679   │     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:99)
 680   │     at io.fabric8.kubernetes.api.model.apps.DoneableStatefulSet.done(DoneableStatefulSet.java:27)
 681   │     at io.fabric8.kubernetes.api.model.apps.DoneableStatefulSet.done(DoneableStatefulSet.java:6)
 682   │     at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:105)
 683   │     at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.replace(RollableScalableResourceOperation.java:159)
 684   │     at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.replace(RollableScalableResourceOperation.java:42)
 685   │     at io.enmasse.controller.standard.KubernetesHelper.apply(KubernetesHelper.java:143)
 686   │     at io.enmasse.controller.standard.KubernetesHelper.apply(KubernetesHelper.java:125)
 687   │     at io.enmasse.controller.standard.AddressController.upgradeClusters(AddressController.java:557)
 688   │     at io.enmasse.controller.standard.AddressController.onUpdate(AddressController.java:421)
 689   │     at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:51)
 690   │     at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:41)
 691   │     at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kornys** [comment]
@lulf I can't see this issue in our standard suite on ocp3.11, but I saw that on ocp4, so I will check it again on different ocp4 server
