### ISSUE TITLE
Unable to deploy enmasse bundle and sharedinfra bundle using fabric8

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#4621]
**Describe the bug**
fabric8 raises issue when it tries to apply files from bundle or sharedinfra bundle

**To Reproduce**
1. Checkout PR #4622 and run any test

**Expected behavior**
fabric8 should be able to deploy files

**Additional context**
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.strimzi-44.openshift-aws.rhocf-dev.com:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: CustomResourceDefinition.apiextensions.k8s.io "messagingendpoints.enmasse.io" is invalid: [spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{ID:"", Schema:"", Ref:(*string)(nil), Description:"", Type:"object", Nullable:false, Format:"", Title:"", Default:(*apiextensions.JSON)(nil), Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]apiextensions.JSON(nil), MaxProperties:(*int64)(nil), MinProperties:(*int64)(nil), Required:[]string(nil), Items:(*apiextensions.JSONSchemaPropsOrArray)(nil), AllOf:[]apiextensions.JSONSchemaProps(nil), OneOf:[]apiextensions.JSONSchemaProps(nil), AnyOf:[]apiextensions.JSONSchemaProps(nil), Not:(*apiextensions.JSONSchemaProps)(nil), Properties:map[string]apiextensions.JSONSchemaProps{"apiVersion":apiextensions.JSONSchemaProps{ID:"", Schema:"", Ref:(*string)(nil), Description:"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources", Type:"string", Nullable:false, Format:"", Title:"", Default:(*apiextensions.JSON)(nil), Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]apiextensions.JSON(nil), MaxProperties:(*int64)(nil), MinProperties:(*int64)(nil), Required:[]string(nil), Items:(*apiextensions.JSONSchemaPropsOrArray)(nil), AllOf:[]apiextensions.JSONSchemaProps(nil), OneOf:[]apiextensions.JSONSchemaProps(nil), AnyOf:[]apiextensions.JSONSchemaProps(nil), Not:(*apiextensions.JSONSchemaProps)(nil), Properties:map[string]apiextensions.JSONSchemaProps(nil), AdditionalProperties:(*apiextensions.JSONSchemaPropsOrBool)(nil), PatternProperties:map[string]apiextensions.JSONSchemaProps(nil), Dependencies:apiextensions.JSONSchemaDependencies(nil), AdditionalItems:(*apiextensions.JSONSchemaPropsOrBool)(nil), Definitions:apiextensions.JSONSchemaDefinitions(nil), ExternalDocs:(*apiextensions.ExternalDocumentation)(nil), Example:(*apiextensions.JSON)(nil), XPreserveUnknownFields:(*bool)(nil), XEmbeddedResource:false, XIntOrString:false, XListMapKeys:[]string(nil), XListType:(*string)(nil), XMapType:(*string)(nil)}, "kind":apiextensions.JSONSchemaProps{ID:"".......
```

**Comment by k-wall** [comment]
@kornys  I think you are hitting https://github.com/fabric8io/kubernetes-client/issues/1486 so I would expect a kubernetes-client upgrade would resolve.   However, I agree with @lulf, our primate interface for deploying the bundle is oc/kubectl , so it is important that this route remains covered by the test suite.

**Comment by kornys** [comment]
oc/kubectl can be used in upgrade tests or somewhere, but anyway I think deploying with fabric8 will be more compoftable for me in test suite

**Comment by kornys** [comment]
so I have just tested that with latest fabric8 clients and yes crds are successfully deployed with fabric8 clients, but one resource not.

```
2020-07-10T10:44:54.100Z [ForkJoinPool-1-worker-3] INFO  [Kubernetes] Processing: /Users/dkornel/redhat/repos/enmasse/systemtests/../templates/build/enmasse-latest/install/bundles/enmasse/020-ClusterRole-qdr-configurator.yaml
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:140)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:101)
	at io.fabric8.kubernetes.client.utils.Serialization.lambda$getKubernetesResourceList$0(Serialization.java:256)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.fabric8.kubernetes.client.utils.Serialization.getKubernetesResourceList(Serialization.java:257)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:99)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:237)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:217)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:156)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.load(DefaultKubernetesClient.java:156)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.load(DefaultOpenShiftClient.java:238)
	at io.enmasse.systemtest.platform.Kubernetes$1.visitFile(Kubernetes.java:1093)
	at io.enmasse.systemtest.platform.Kubernetes$1.visitFile(Kubernetes.java:1066)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at io.enmasse.systemtest.platform.Kubernetes.loadDirectory(Kubernetes.java:1066)
	at io.enmasse.systemtest.platform.Kubernetes.loadDirectories(Kubernetes.java:1055)
	at io.enmasse.systemtest.platform.Kubernetes.apply(Kubernetes.java:1034)
	at io.enmasse.systemtest.platform.Kubernetes.apply(Kubernetes.java:1040)
	at io.enmasse.systemtest.operator.EnmasseOperatorManager.installEnmasseBundle(EnmasseOperatorManager.java:69)
	at io.enmasse.systemtest.framework.TestLifecycleManager.lambda$beforeAll$0(TestLifecycleManager.java:41)
	at io.enmasse.systemtest.framework.TestLifecycleManager.handleCallBackError(TestLifecycleManager.java:112)
	at io.enmasse.systemtest.framework.TestLifecycleManager.beforeAll(TestLifecycleManager.java:39)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:rbac.authorization.k8s.io/v1beta1#ClusterRole
 at [Source: (BufferedInputStream); line: 17, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:85)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:57)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:138)
	... 59 more
```

**Comment by lulf** [comment]
That ClusterRole should be changed from v1beta1 to v1 I think @kornys

**Comment by kornys** [comment]
@lulf yes that helped :) thank you I will open PR with update to v1

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/4942
