### ISSUE TITLE
StackOverflowError from standard-controller after long uptime

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#4653]
**Describe the bug**

A EnMasse 0.30 derivate suffered the following java.lang.StackOverflowError after 3120h uptime.  The error killed the resource checker thread (from which it did not recover), so no further reconciliation were performed until the admin pod was manually restarted.

```
2020-05-25T17:33:14.194Z INFO  [RouterStatusCache] Collecting status from 2 routers
Exception in thread "resource-checker" java.lang.StackOverflowError
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034)
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034)
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034)
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034)
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034)
        at java.base/java.util.Collections$UnmodifiableCollection.size(Collections.java:1034

``` 

**To Reproduce**

Not known

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by k-wall** [comment]
I've been unable to reproduce this error or the unmodifiable collections wrapping issue that lead to it.  I tried running with a conditional break points in the UnmodifiableCollection class that break if the target collection is already unmodifiable whilst adding/removing addresses.  

I did see one instance where the Hibernate Validator created a unmodifiable wrapping unmodifiables but the instance seemed shorted live.  I was unable to reproduce the issue again investigate further.  The stack trace looked similar to this: https://hibernate.atlassian.net/browse/HV-1684

**Comment by lulf** [comment]
I ran an experiment creating/deleting addresses over a long period of time and comparing heap dumps, without finding any difference in the UnmodifiableCollection objects in the heaps. I think we can close this for now and assume that Hibernate Validator fix will prevent this from happening again.
