### ISSUE TITLE
Missing auto links following a mirco upgrade

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#5228]
**Describe the bug**

Since #5210, upgrades from earlier versions have the potential to fail leaving addresses in an unready state.

```
xxxxxxx  yyyyyyyyyyyyyyyyy       zzzzzzzzzzzzzzzzz        queue     standard-small-queue    false     Active    [Address yyyyyyyyyyyyyyyyy is missing active autoLink (active in dirs: [])]        162d
```

Examining the broker log will show that the connectors have failed like this:
 
```
{{2021-01-05T11:15:53.090Z INFO [server] AMQ221022: unable to start connector service: $override-router-connector-out: java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.parseInt(Integer.java:615)
at java.util.Optional.map(Optional.java:215)
at org.apache.activemq.artemis.integration.amqp.AMQPConnectorServiceFactory.createConnectorService(AMQPConnectorServiceFactory.java:135)
at org.apache.activemq.artemis.core.server.impl.ConnectorsService.createService(ConnectorsService.java:105)
at org.apache.activemq.artemis.core.server.impl.ConnectorsService.start(ConnectorsService.java:80)
at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:637)
at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:526)
at org.apache.activemq.artemis.integration.FileBroker.start(FileBroker.java:70)
at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:84)
at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:153)
at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:101)
at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:128)}}
```

**Comment by k-wall** [comment]
The issue is broker plugin code requires that the `MIN_LARGE_MESSAGE_SIZE` environment variable is set within the init container.  This variable won't be set unless the standard controller has to rewrite the broker statefulset definition.

**Comment by k-wall** [comment]
To workaround this issue, give the `minLargeMessageSize` its default value explicitly in the standardinfraconfig.

```
oc patch standardinfraconfig -n enmasse-infra default --type=json --patch '[{"op":"add","path":"/spec/broker/minLargeMessageSize","value":-1}]'
```
