### ISSUE TITLE
Address-controller:  Exception doing resource update java.lang.NullPointerException

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#672]
Following NPE is several times presented in address-controller log after address space was created.

I'll try to reproduce it locally and I'll add more info.

```
2017-12-20 05:50:01 INFO  OpenSSLCertManager:129 - unable to write 'random state'
2017-12-20 05:50:01 INFO  AuthController:88 - Issued component certificates: [{name=agent,secretName=agent-internal-cert,namespace=brokered-default-0}, {name=broker,secretName=broker-internal-cert,namespace=brokered-default-0}]
2017-12-20 05:50:01 WARN  ResourceController:75 - Exception doing resource update
java.lang.NullPointerException
	at io.enmasse.controller.auth.AuthController.issueExternalCertificates(AuthController.java:49)
	at io.enmasse.controller.Controller.resourcesUpdated(Controller.java:130)
	at io.enmasse.k8s.api.ResourceController.run(ResourceController.java:72)
	at java.lang.Thread.run(Thread.java:748)
2017-12-20 05:50:14 INFO  OpenSSLCertManager:60 - Creating self-signed certificates for external-certs-console
2017-12-20 05:50:14 INFO  OpenSSLCertManager:121 - Running command '[openssl, req, -new, -days, 11000, -x509, -batch, -nodes, -out, /tmp/tls902605132804410397crt, -keyout, /tmp/tls5218077405032595564key]'
```

**Comment by tkratky** [comment]
@grs:
reproducible via following test: (but probably reproducible by any test which creates address-space)

`make MULTITENANT=true SYSTEMTEST_ARGS='io.enmasse.systemtest.auth.AuthenticationTest#testStandardAuthenticationService' systemtests`

**Comment by lulf** [comment]
See https://github.com/EnMasseProject/enmasse/commit/1621c80e7a2d758b1187e0f6e3d75a7c4b45afe9#comments

**Comment by lulf** [comment]
Fix is merged to master
