### ISSUE TITLE
Error creating brokered address space in enmasse using REST API

### ISSUE THREAD

**Issue by nandanj** [EnMasseProject/enmasse#812]
Problem reproducible in 0.15.3 as well as 0.16 rc2. Enmasse deployment on oc 3.7.14.

here's the .json

{
    "apiVersion": "v1/enmasse",
    "kind": "AddressSpace",
    "metadata": {
        "name": "brokerspace"
    },
    "spec": {
        "type": "brokered"
    }
}

And here's the output from the curl command

% curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" @braddrspace.json -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1/addressspaces/
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

And here's the error on the address controller

2018-01-26 20:45:56 WARN  DefaultExceptionMapper:32 - Returning server error HTTP status 500

java.lang.NullPointerException
	at io.enmasse.controller.api.v1.http.HttpAddressSpaceService.createAddressSpace(HttpAddressSpaceService.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
	at org.jboss.resteasy.plugins.server.vertx.RequestDispatcher.service(RequestDispatcher.java:93)
	at org.jboss.resteasy.plugins.server.vertx.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:65)
	at io.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:214)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:418)
	at io.vertx.core.http.impl.ServerConnection.handleLastHttpContent(ServerConnection.java:475)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:446)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:156)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:705)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:614)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by grs** [comment]
Missing --data-binary, e.g.:

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" --data-binary @braddrspace.json -k https://$(oc get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1/addressspaces/
