### ISSUE TITLE
Standard: message browsing does not work in standard address space.

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#838]
When receiver tries to receive message with browse enabled, it takes message so another receiver cannot see this message.

recv browsing of queue does not work in standard address space, in brokered works well. I think that must be router issue.

reproducer:
1. create standard address space
2. create queue "message-browse"
3. run following commands
```sh
pip install cli-proton-python
cli-proton-python-sender --broker amqps://test:test@<messaging-route>:443/message-browse --count 1 --log-lib TRANSPORT_FRM --log-msgs json
cli-proton-python-receiver --broker amqps://test:test@<messaging-route>:443/message-browse --count 1 --log-lib TRANSPORT_FRM --log-msgs json --recv-browse True
cli-proton-python-receiver --broker amqps://test:test@<messaging-route>:443/message-browse --count 1 --log-lib TRANSPORT_FRM --log-msgs json
```

automated test: in branch **standard-space-clients-tests**
```sh
make MULTITENANT=true SYSTEMTEST_ARGS='standard.clients.proton.python.MsgPatternsTest#testMessageBrowse' systemtests
```

output:
```
$ cli-proton-python-sender --broker amqps://test:test@messaging-standard-shared-0.***.nip.io:443/message-browse --count 1 --log-msgs json --log-lib TRANSPORT_FRM
[0x11903d0]:  -> SASL
[0x11903d0]:  <- SASL
[0x11903d0]:0 <- @sasl-mechanisms(64) [sasl-server-mechanisms=@PN_SYMBOL[:PLAIN, :"SCRAM-SHA-1", :"SCRAM-SHA-256", :"SCRAM-SHA-512"]]
[0x11903d0]:0 -> @sasl-init(65) [mechanism=:PLAIN, initial-response=b"\x00test\x00test"]
[0x11903d0]:0 <- @sasl-outcome(68) [code=0]
[0x11903d0]:  -> AMQP
[0x11903d0]:0 -> @open(16) [container-id="b4363c97-4ee6-4fcc-9b0e-6231ab61ded5", hostname="messaging-standard-shared-0.***.nip.io", channel-max=32767]
[0x11903d0]:0 -> @begin(17) [next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x11903d0]:0 -> @attach(18) [name="b4363c97-4ee6-4fcc-9b0e-6231ab61ded5-message-browse", handle=0, role=false, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [durable=0, timeout=0, dynamic=false], target=@target(41) [address="message-browse", durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x11903d0]:  <- AMQP
[0x11903d0]:0 <- @open(16) [container-id="Router.qdrouterd-2874835354-8jzl7", max-frame-size=16384, channel-max=32767, idle-time-out=8000, offered-capabilities=:"ANONYMOUS-RELAY", properties={:product="qpid-dispatch-router", :version="1.0.0"}]
[0x11903d0]:0 <- @begin(17) [remote-channel=0, next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x11903d0]:0 <- @attach(18) [name="b4363c97-4ee6-4fcc-9b0e-6231ab61ded5-message-browse", handle=0, role=true, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [durable=0, timeout=0, dynamic=false], target=@target(41) [address="message-browse", durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x11903d0]:0 <- @flow(19) [next-incoming-id=0, incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=0, link-credit=250, drain=false]
{"priority": 4, "creation-time": 0, "first-acquirer": false, "group-id": null, "content-encoding": null, "ttl": 0, "delivery-count": 0, "durable": false, "reply-to-group-id": null, "correlation-id": null, "absolute-expiry-time": 0, "properties": {}, "content": null, "user-id": null, "address": null, "reply-to": null, "subject": null, "content-type": "text/plain", "id": null, "group-sequence": 0}
[0x11903d0]:0 -> @transfer(20) [handle=0, delivery-id=0, delivery-tag=b"1", message-format=0, settled=false, more=false, resume=false, aborted=false, batchable=false] (84) "\x00Sp\xd0\x00\x00\x00\x0b\x00\x00\x00\x05BP\x04@BR\x00\x00Ss\xd0\x00\x00\x00-\x00\x00\x00\x0d@@@@@@\xa3\x0atext/plain@\x83\x00\x00\x00\x00\x00\x00\x00\x00\x83\x00\x00\x00\x00\x00\x00\x00\x00@R\x00@\x00St\xd1\x00\x00\x00\x04\x00\x00\x00\x00"
[0x11903d0]:0 <- @flow(19) [next-incoming-id=1, incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=1, link-credit=250, drain=false]
[0x11903d0]:0 <- @disposition(21) [role=true, first=0, last=0, settled=true, state=@accepted(36) []]
[0x11903d0]:0 -> @detach(22) [handle=0, closed=true]
[0x11903d0]:0 -> @close(24) []
[0x11903d0]:0 <- @close(24) []
[0x11903d0]:  <- EOS
[0x11903d0]:  -> EOS
$ cli-proton-python-receiver --broker amqps://test:test@messaging-standard-shared-0.***.nip.io:443/message-browse --count 1 --log-msgs json --log-lib TRANSPORT_FRM -- recv-browse True
[0x1dc3690]:  -> SASL
[0x1dc3690]:  <- SASL
[0x1dc3690]:0 <- @sasl-mechanisms(64) [sasl-server-mechanisms=@PN_SYMBOL[:PLAIN, :"SCRAM-SHA-1", :"SCRAM-SHA-256", :"SCRAM-SHA-512"]]
[0x1dc3690]:0 -> @sasl-init(65) [mechanism=:PLAIN, initial-response=b"\x00test\x00test"]
[0x1dc3690]:0 <- @sasl-outcome(68) [code=0]
[0x1dc3690]:  -> AMQP
[0x1dc3690]:0 -> @open(16) [container-id="94e95bf6-76ae-405d-a86f-68f825031601", hostname="messaging-standard-shared-0.***.nip.io", channel-max=32767]
[0x1dc3690]:0 -> @begin(17) [next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x1dc3690]:0 -> @attach(18) [name="94e95bf6-76ae-405d-a86f-68f825031601-message-browse", handle=0, role=true, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [address="message-browse", durable=0, timeout=0, dynamic=false, distribution-mode=:copy], target=@target(41) [durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x1dc3690]:0 -> @flow(19) [incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=0, link-credit=10, drain=false]
[0x1dc3690]:  <- AMQP
[0x1dc3690]:0 <- @open(16) [container-id="Router.qdrouterd-2874835354-8jzl7", max-frame-size=16384, channel-max=32767, idle-time-out=8000, offered-capabilities=:"ANONYMOUS-RELAY", properties={:product="qpid-dispatch-router", :version="1.0.0"}]
[0x1dc3690]:0 <- @begin(17) [remote-channel=0, next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x1dc3690]:0 <- @attach(18) [name="94e95bf6-76ae-405d-a86f-68f825031601-message-browse", handle=0, role=false, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [address="message-browse", durable=0, timeout=0, dynamic=false, distribution-mode=:copy], target=@target(41) [durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x1dc3690]:0 <- @transfer(20) [handle=0, delivery-id=0, delivery-tag=b"Z\x04\x00\x00\x00\x00\x00\x00", message-format=0, settled=false, more=false, resume=false, aborted=false, batchable=false] (84) "\x00Sp\xd0\x00\x00\x00\x0b\x00\x00\x00\x05BP\x04@BR\x00\x00Ss\xd0\x00\x00\x00-\x00\x00\x00\x0d@@@@@@\xa3\x0atext/plain@\x83\x00\x00\x00\x00\x00\x00\x00\x00\x83\x00\x00\x00\x00\x00\x00\x00\x00@R\x00@\x00St\xd1\x00\x00\x00\x04\x00\x00\x00\x00"
{"priority": 4, "creation-time": 0, "first-acquirer": false, "group-id": null, "content-encoding": null, "ttl": 0, "delivery-count": 0, "durable": false, "reply-to-group-id": null, "correlation-id": null, "absolute-expiry-time": 0, "properties": {}, "content": null, "user-id": null, "address": null, "reply-to": null, "subject": null, "content-type": "text/plain", "id": null, "group-sequence": 0}
[0x1dc3690]:0 -> @disposition(21) [role=true, first=0, last=0, settled=true, state=@accepted(36) []]
[0x1dc3690]:0 -> @detach(22) [handle=0, closed=true]
[0x1dc3690]:0 -> @close(24) []
[0x1dc3690]:0 <- @close(24) []
[0x1dc3690]:  <- EOS
[0x1dc3690]:  -> EOS
$ cli-proton-python-receiver --broker amqps://test:test@messaging-standard-shared-0.***.nip.io:443/message-browse --count 1 --log-msgs json --log-lib TRANSPORT_FRM -- recv-browse True
[0x26f2690]:  -> SASL
[0x26f2690]:  <- SASL
[0x26f2690]:0 <- @sasl-mechanisms(64) [sasl-server-mechanisms=@PN_SYMBOL[:PLAIN, :"SCRAM-SHA-1", :"SCRAM-SHA-256", :"SCRAM-SHA-512"]]
[0x26f2690]:0 -> @sasl-init(65) [mechanism=:PLAIN, initial-response=b"\x00test\x00test"]
[0x26f2690]:0 <- @sasl-outcome(68) [code=0]
[0x26f2690]:  -> AMQP
[0x26f2690]:0 -> @open(16) [container-id="8e938ade-fad8-4438-8d6f-c0aeecb8e2f3", hostname="messaging-standard-shared-0.***.nip.io", channel-max=32767]
[0x26f2690]:0 -> @begin(17) [next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x26f2690]:0 -> @attach(18) [name="8e938ade-fad8-4438-8d6f-c0aeecb8e2f3-message-browse", handle=0, role=true, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [address="message-browse", durable=0, timeout=0, dynamic=false, distribution-mode=:copy], target=@target(41) [durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x26f2690]:0 -> @flow(19) [incoming-window=2147483647, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=0, link-credit=10, drain=false]
[0x26f2690]:  <- AMQP
[0x26f2690]:0 <- @open(16) [container-id="Router.qdrouterd-2874835354-8jzl7", max-frame-size=16384, channel-max=32767, idle-time-out=8000, offered-capabilities=:"ANONYMOUS-RELAY", properties={:product="qpid-dispatch-router", :version="1.0.0"}]
[0x26f2690]:0 <- @begin(17) [remote-channel=0, next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x26f2690]:0 <- @attach(18) [name="8e938ade-fad8-4438-8d6f-c0aeecb8e2f3-message-browse", handle=0, role=false, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [address="message-browse", durable=0, timeout=0, dynamic=false, distribution-mode=:copy], target=@target(41) [durable=0, timeout=0, dynamic=false], initial-delivery-count=0, max-message-size=0]
[0x26f2690]:0 -> (EMPTY FRAME)
[0x26f2690]:0 -> (EMPTY FRAME)
Traceback (most recent call last):
  File "/usr/bin/cli-proton-python-receiver", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/cli_proton_python/receiver.py", line 514, in main
    container.run()
  File "/usr/lib64/python2.7/site-packages/proton/reactor.py", line 148, in run
    while self.process(): pass
  File "/usr/lib64/python2.7/site-packages/proton/reactor.py", line 174, in process
    self._check_errors()
  File "/usr/lib64/python2.7/site-packages/proton/reactor.py", line 170, in _check_errors
    _compat.raise_(exc, value, tb)
  File "/usr/lib64/python2.7/site-packages/proton/__init__.py", line 4081, in dispatch
    ev.dispatch(self.handler)
  File "/usr/lib64/python2.7/site-packages/proton/__init__.py", line 3990, in dispatch
    result = dispatch(handler, type.method, self)
  File "/usr/lib64/python2.7/site-packages/proton/__init__.py", line 3870, in dispatch
    return handler.on_unhandled(method, *args)
  File "/usr/lib64/python2.7/site-packages/proton/reactor.py", line 531, in on_unhandled
    event.dispatch(self.base)
  File "/usr/lib64/python2.7/site-packages/proton/__init__.py", line 3988, in dispatch
    pn_handler_dispatch(handler._impl, self._impl, type.number)
KeyboardInterrupt
```

**Comment by kornys** [comment]
Closed as not supported functionality
