### ISSUE TITLE
Standard: qpid jms client cannot authenticate using SCRAM-SHA-256

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#840]
reproducer:
1. Create standard address space
2. Create queue test-queue
3. Run the following commands
```sh
cd enmasse
make client_install
java -jar systemtests/client_executable/cli-qpid-jms.jar sender --count 5 --log-msgs json --broker-uri "amqps://<messaging-route>:443/test-queue ?jms.username=test&jms.password=test&transport.trustAll=true&transport.verifyHost=false"
```

output
```
$ java -jar systemtests/client_executable/cli-qpid-jms.jar sender --count 5 --log-msgs json --broker-uri "amqps://<messaging-route>:443/test-queue ?jms.username=test&jms.password=test&transport.trustAll=true&transport.verifyHost=false"
19:41:26,089 ERROR Failed to connect to remote at: amqps://<messaging-route>:443/test-queue?transport.trustAll=true&transport.verifyHost=false
19:41:26,101 ERROR Client failed to authenticate using SASL: SCRAM-SHA-256
javax.jms.JMSSecurityException: Client failed to authenticate using SASL: SCRAM-SHA-256
        at org.apache.qpid.jms.provider.amqp.AmqpSaslAuthenticator.recordFailure(AmqpSaslAuthenticator.java:146)
        at org.apache.qpid.jms.provider.amqp.AmqpSaslAuthenticator.handleSaslFail(AmqpSaslAuthenticator.java:125)
        at org.apache.qpid.jms.provider.amqp.AmqpSaslAuthenticator.handleSaslOutcome(AmqpSaslAuthenticator.java:108)
        at org.apache.qpid.jms.provider.amqp.AmqpProvider.onSaslOutcome(AmqpProvider.java:885)
        at org.apache.qpid.proton.engine.impl.SaslImpl.handleOutcome(SaslImpl.java:440)
        at org.apache.qpid.proton.engine.impl.SaslImpl.handleOutcome(SaslImpl.java:49)
        at org.apache.qpid.proton.amqp.security.SaslOutcome.invoke(SaslOutcome.java:75)
        at org.apache.qpid.proton.engine.impl.SaslImpl.handle(SaslImpl.java:334)
        at org.apache.qpid.proton.engine.impl.SaslFrameParser.input(SaslFrameParser.java:367)
        at org.apache.qpid.proton.engine.impl.SaslImpl$SaslTransportWrapper.reallyProcessInput(SaslImpl.java:659)
        at org.apache.qpid.proton.engine.impl.SaslImpl$SaslTransportWrapper.process(SaslImpl.java:630)
        at org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.process(HandshakeSniffingTransportWrapper.java:101)
        at org.apache.qpid.proton.engine.impl.TransportImpl.process(TransportImpl.java:1495)
        at org.apache.qpid.proton.engine.impl.TransportImpl.processInput(TransportImpl.java:1453)
        at org.apache.qpid.jms.provider.amqp.AmqpProvider$17.run(AmqpProvider.java:786)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

qdrouter
```
2018-02-04 18:35:28.104460 +0000 SERVER (info) Connection from 172.17.0.1:58294 (to 0.0.0.0:5671) failed: amqp:unauthorized-access Failed to authenticate client [mech=SCRAM-SHA-256]
```

**Comment by kornys** [comment]
Fixed by adding amqp.saslMechanisms=PLAIN to broker-uri. JMS client can authenticate to queue.
