### ISSUE TITLE
Error in admin pod

### ISSUE THREAD

**Issue by calohmn** [EnMasseProject/enmasse#955]
We got the following errors in the admin pod with EnMasse 0.17.0:
````
2018-02-27T15:37:05.072Z agent info GET /api/v1/namespaces/hono/configmaps?labelSelector=type%3Daddress-plan => 200 
2018-02-27T15:37:05.073Z agent info list retrieved; watching...
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-pooled-queue","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-pooled-queue","uid":"83a7a04a-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019186","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"pooled-queue\\\"\\n  },\\n  \\\"displayName\\\": \\\"Pooled Queue\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a queue on a pooled broker.\\\",\\n  \\\"longDescription\\\": \\\"Creates a queue on a pooled broker shared with other queues.\\\",\\n  \\\"uuid\\\": \\\"0843743a-0503-11e8-91df-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"queue\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    },\\n    {\\n      \\\"name\\\": \\\"broker\\\",\\n      \\\"credit\\\": 0.01\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-pooled-queue\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"pooled-queue\"\n  },\n  \"displayName\": \"Pooled Queue\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a queue on a pooled broker.\",\n  \"longDescription\": \"Creates a queue on a pooled broker shared with other queues.\",\n  \"uuid\": \"0843743a-0503-11e8-91df-507b9def37d9\",\n  \"addressType\": \"queue\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    },\n    {\n      \"name\": \"broker\",\n      \"credit\": 0.01\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-pooled-topic","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-pooled-topic","uid":"83e317a7-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019191","creationTimestamp":"2018-02-27T11:01:09Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"pooled-topic\\\"\\n  },\\n  \\\"displayName\\\": \\\"Pooled Topic\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a topic on a shared broker.\\\",\\n  \\\"longDescription\\\": \\\"Creates a topic on a shared broker with other topics.\\\",\\n  \\\"uuid\\\": \\\"45e0bc24-155e-11e8-8962-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"topic\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    },\\n    {\\n      \\\"name\\\": \\\"broker\\\",\\n      \\\"credit\\\": 0.01\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-pooled-topic\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"pooled-topic\"\n  },\n  \"displayName\": \"Pooled Topic\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a topic on a shared broker.\",\n  \"longDescription\": \"Creates a topic on a shared broker with other topics.\",\n  \"uuid\": \"45e0bc24-155e-11e8-8962-507b9def37d9\",\n  \"addressType\": \"topic\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    },\n    {\n      \"name\": \"broker\",\n      \"credit\": 0.01\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-sharded-queue","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-sharded-queue","uid":"83990a24-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019185","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"sharded-queue\\\"\\n  },\\n  \\\"displayName\\\": \\\"Sharded Queue\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a queue on a standalone broker.\\\",\\n  \\\"longDescription\\\": \\\"Creates a queue on a standalone broker that can be sharded.\\\",\\n  \\\"uuid\\\": \\\"aeddd606-0502-11e8-ad75-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"queue\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    },\\n    {\\n      \\\"name\\\": \\\"broker\\\",\\n      \\\"credit\\\": 1.0\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-sharded-queue\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"sharded-queue\"\n  },\n  \"displayName\": \"Sharded Queue\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a queue on a standalone broker.\",\n  \"longDescription\": \"Creates a queue on a standalone broker that can be sharded.\",\n  \"uuid\": \"aeddd606-0502-11e8-ad75-507b9def37d9\",\n  \"addressType\": \"queue\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    },\n    {\n      \"name\": \"broker\",\n      \"credit\": 1.0\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-sharded-topic","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-sharded-topic","uid":"83d4d967-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019190","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"sharded-topic\\\"\\n  },\\n  \\\"displayName\\\": \\\"Sharded Topic\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a topic on a standalone broker.\\\",\\n  \\\"longDescription\\\": \\\"Creates a topic on a standalone broker that can be sharded.\\\",\\n  \\\"uuid\\\": \\\"de256d34-0502-11e8-98c9-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"topic\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    },\\n    {\\n      \\\"name\\\": \\\"broker\\\",\\n      \\\"credit\\\": 1.0\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-sharded-topic\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"sharded-topic\"\n  },\n  \"displayName\": \"Sharded Topic\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a topic on a standalone broker.\",\n  \"longDescription\": \"Creates a topic on a standalone broker that can be sharded.\",\n  \"uuid\": \"de256d34-0502-11e8-98c9-507b9def37d9\",\n  \"addressType\": \"topic\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    },\n    {\n      \"name\": \"broker\",\n      \"credit\": 1.0\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-standard-anycast","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-standard-anycast","uid":"83b64432-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019187","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"standard-anycast\\\"\\n  },\\n  \\\"displayName\\\": \\\"Standard\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a direct anycast address.\\\",\\n  \\\"longDescription\\\": \\\"Creates a direct anycast address where messages go via a router that does not take ownership of the messages.\\\",\\n  \\\"uuid\\\": \\\"45edd942-0503-11e8-84ce-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"anycast\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-standard-anycast\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"standard-anycast\"\n  },\n  \"displayName\": \"Standard\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a direct anycast address.\",\n  \"longDescription\": \"Creates a direct anycast address where messages go via a router that does not take ownership of the messages.\",\n  \"uuid\": \"45edd942-0503-11e8-84ce-507b9def37d9\",\n  \"addressType\": \"anycast\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-standard-multicast","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-standard-multicast","uid":"83c4b4be-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019188","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"standard-multicast\\\"\\n  },\\n  \\\"displayName\\\": \\\"Standard\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a direct multicast address.\\\",\\n  \\\"longDescription\\\": \\\"Creates a direct multicast address where messages go via a router that does not take ownership of the messages.\\\",\\n  \\\"uuid\\\": \\\"60fc2702-0503-11e8-b60e-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"multicast\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-standard-multicast\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"standard-multicast\"\n  },\n  \"displayName\": \"Standard\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a direct multicast address.\",\n  \"longDescription\": \"Creates a direct multicast address where messages go via a router that does not take ownership of the messages.\",\n  \"uuid\": \"60fc2702-0503-11e8-b60e-507b9def37d9\",\n  \"addressType\": \"multicast\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    }\n  ]\n}"}}
Failed to parse config.json for address: SyntaxError: Unexpected token u in JSON at position 0 {"metadata":{"name":"address-plan-pooled-queue","namespace":"hono","selfLink":"/api/v1/namespaces/hono/configmaps/address-plan-pooled-queue","uid":"83a7a04a-1bad-11e8-9dea-0a8c7df215b0","resourceVersion":"1019186","creationTimestamp":"2018-02-27T11:01:08Z","labels":{"type":"address-plan"},"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"data\":{\"definition\":\"{\\n  \\\"apiVersion\\\": \\\"enmasse.io/v1\\\",\\n  \\\"kind\\\": \\\"AddressPlan\\\",\\n  \\\"metadata\\\": {\\n    \\\"name\\\": \\\"pooled-queue\\\"\\n  },\\n  \\\"displayName\\\": \\\"Pooled Queue\\\",\\n  \\\"displayOrder\\\": 0,\\n  \\\"shortDescription\\\": \\\"Creates a queue on a pooled broker.\\\",\\n  \\\"longDescription\\\": \\\"Creates a queue on a pooled broker shared with other queues.\\\",\\n  \\\"uuid\\\": \\\"0843743a-0503-11e8-91df-507b9def37d9\\\",\\n  \\\"addressType\\\": \\\"queue\\\",\\n  \\\"requiredResources\\\": [\\n    {\\n      \\\"name\\\": \\\"router\\\",\\n      \\\"credit\\\": 0.01\\n    },\\n    {\\n      \\\"name\\\": \\\"broker\\\",\\n      \\\"credit\\\": 0.01\\n    }\\n  ]\\n}\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"type\":\"address-plan\"},\"name\":\"address-plan-pooled-queue\",\"namespace\":\"hono\"}}\n"}},"data":{"definition":"{\n  \"apiVersion\": \"enmasse.io/v1\",\n  \"kind\": \"AddressPlan\",\n  \"metadata\": {\n    \"name\": \"pooled-queue\"\n  },\n  \"displayName\": \"Pooled Queue\",\n  \"displayOrder\": 0,\n  \"shortDescription\": \"Creates a queue on a pooled broker.\",\n  \"longDescription\": \"Creates a queue on a pooled broker shared with other queues.\",\n  \"uuid\": \"0843743a-0503-11e8-91df-507b9def37d9\",\n  \"addressType\": \"queue\",\n  \"requiredResources\": [\n    {\n      \"name\": \"router\",\n      \"credit\": 0.01\n    },\n    {\n      \"name\": \"broker\",\n      \"credit\": 0.01\n    }\n  ]\n}"}}
/opt/app-root/src/lib/internal_address_source.js:58
        console.error('Failed to parse config.json for address: %s %j', e, object);
                                                                           ^

ReferenceError: object is not defined
    at extract_spec (/opt/app-root/src/lib/internal_address_source.js:58:76)
    at extract_address_spec (/opt/app-root/src/lib/internal_address_source.js:63:12)
    at Array.map (native)
    at AddressSource.updated (/opt/app-root/src/lib/internal_address_source.js:94:48)
    at emitOne (events.js:96:13)
    at Watcher.emit (events.js:188:7)
    at Immediate.<anonymous> (/opt/app-root/src/lib/kubernetes.js:155:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
````

**Comment by grs** [comment]
There are two issues here. The first, inability to parse the json, is the root cause. Can you attach the yaml or json for one of the configmaps containing one of these plans? I can see if I can reproduce quickly with that.

The second error is just broken error handling which is an easy fix.

**Comment by calohmn** [comment]
@grs the yamls for these plans are all in "standard-plans.yaml", unchanged from the 0.17.0 release zip.

**Comment by grs** [comment]
The root cause, the syntax error, should be fixed by https://github.com/EnMasseProject/enmasse/pull/1012
