### ISSUE TITLE
Credit limitations, cannot create topic with custom plan.

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#960]
I have followed this scenarios https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/design/resource-scheduler.adoc#testing and **scenario3** does not work. It tries to create 2 topics, test stuck on phase Waiting for 7 pods, but only one broker pod was created, but standard-controller shows both addresses are ready and Active.

standard controller log:
[admin-3310450726-b5dvb.standard-controller.txt](https://github.com/EnMasseProject/enmasse/files/1766385/admin-3310450726-b5dvb.standard-controller.txt)

Full output is in Jenkins -> Enmasse pull request -> enmasse -> test-credit-limitations -> 17

test is **testQuotaLimits** in branch **test-credit-limitations** #953

output from test
```
03:49:11,371 [main] INFO io.enmasse.systemtest.AddressApiClient - Deploying using path /apis/enmasse.io/v1/addresses/test1/ and body: {"apiVersion":"v1","kind":"AddressList","items":[{"metadata":{"name":"t1","addressSpace":"test1"},"spec":{"address":"t1","type":"topic","plan":"queue-test2"}},{"metadata":{"name":"t2","addressSpace":"test1"},"spec":{"address":"t2","type":"topic","plan":"queue-test2"}}]}

03:49:13,503 [main] INFO io.enmasse.systemtest.TestUtils - Waiting for 7 pods

03:54:12,335 [main] INFO io.enmasse.systemtest.AddressApiClient - Following HTTP request will be used for getting address space:/apis/enmasse.io/v1/addressspaces with host: restapi-enmasse-pr-enma17.127.0.0.1.nip.io with Port: 443
03:54:13,368 [main] INFO io.enmasse.systemtest.AddressApiClient - Following list of address spaces received[{"metadata":{"name":"test1","namespace":"test1","createdBy":"****"},"spec":{"type":"standard","plan":"test1","endpoints":[{"name":"console","service":"console","host":"console-test1.127.0.0.1.nip.io","port":443,"certProvider":{"name":"selfsigned","secretName":"external-certs-console"}},{"name":"messaging","service":"messaging","host":"messaging-test1.127.0.0.1.nip.io","port":443,"certProvider":{"name":"selfsigned","secretName":"external-certs-messaging"}},{"name":"mqtt","service":"mqtt","host":"mqtt-test1.127.0.0.1.nip.io","port":443,"certProvider":{"name":"selfsigned","secretName":"external-certs-mqtt"}}],"authenticationService":{"type":"standard","details":{}}},"status":{"isReady":true}}]
03:54:13,390 [main] INFO io.enmasse.systemtest.GlobalLogCollector - Store logs from all terminated pods in namespace 'test1'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'admin-3310450726-b5dvb' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'admin-3310450726-b5dvb' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'broker-0' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'mqtt-gateway-1075114327-3b3w8' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'mqtt-gateway-1075114327-3b3w8' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'mqtt-lwt-3802636231-z4544' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'qdrouterd-338925236-w7801' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'qdrouterd-338925236-w7801' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.Kubernetes - pod:'subserv-2668314260-vh8kd' : restart count '0'
03:54:13,395 [main] INFO io.enmasse.systemtest.AddressApiClient - Following HTTP request will be used for removing address space: '/apis/enmasse.io/v1/addressspaces/test1'

03:54:54,643 [main] INFO io.enmasse.systemtest.GlobalLogCollector - Stop collecting logs for pods in namespace test1
03:54:54,652 [main] ERROR io.enmasse.systemtest.bases.SystemTestRunListener - Caught exception {}
java.lang.IllegalStateException: Unable to find 7 pods. Found : admin-3310450726-b5dvb,broker-0,mqtt-gateway-1075114327-3b3w8,mqtt-lwt-3802636231-z4544,qdrouterd-338925236-w7801,subserv-2668314260-vh8kd
	at io.enmasse.systemtest.TestUtils.waitForExpectedPods(TestUtils.java:135)
	at io.enmasse.systemtest.TestUtils.deploy(TestUtils.java:199)
	at io.enmasse.systemtest.bases.TestBase.setAddresses(TestBase.java:168)
	at io.enmasse.systemtest.plans.PlansTest.checkLimits(PlansTest.java:175)
	at io.enmasse.systemtest.plans.PlansTest.testQuotaLimits(PlansTest.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
03:54:54,655 [main] INFO io.enmasse.systemtest.bases.SystemTestRunListener - testQuotaLimits(io.enmasse.systemtest.plans.PlansTest)FINISHED
03:54:54,655 [main] INFO io.enmasse.systemtest.bases.SystemTestRunListener - ###########################################################
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1,225.934 s <<< FAILURE! - in io.enmasse.systemtest.plans.PlansTest
[ERROR] testQuotaLimits(io.enmasse.systemtest.plans.PlansTest)  Time elapsed: 1,225.925 s  <<< ERROR!
java.lang.IllegalStateException: Unable to find 7 pods. Found : admin-3310450726-b5dvb,broker-0,mqtt-gateway-1075114327-3b3w8,mqtt-lwt-3802636231-z4544,qdrouterd-338925236-w7801,subserv-2668314260-vh8kd
	at io.enmasse.systemtest.plans.PlansTest.checkLimits(PlansTest.java:175)
	at io.enmasse.systemtest.plans.PlansTest.testQuotaLimits(PlansTest.java:162)
```

**Comment by kornys** [comment]
should be fixed by https://github.com/EnMasseProject/enmasse/pull/953/commits/1882a3a491188e532af9aabdaf2414748e1711ba
